# Lakewood Ranch Concrete &mdash; city data (part 4 of 4)
CITIES = {
    "osprey": {
        "name": "Osprey",
        "slug": "osprey",
        "county": "Sarasota County",
        "state": "FL",
        "zips": ["34229"],
        "population": "6,500+",
        "growth": "Steady affluent growth 2020&ndash;2025",
        "lat": "27.1956",
        "lng": "-82.4904",
        "neighborhoods": [
            "The Oaks","Rivendell","Southbay Yacht & Racquet Club","Bay Street","Willowbend",
            "Park Trace","Sorrento Woods","Oaks Bayside","Oaks Clubside","Baystreet Village",
            "Pine Run","Bellwood","Edgewater at Hidden Bay","Osprey Harbor Village","Blackburn Point"
        ],
        "context": "Osprey sits in the affluent stretch of the Sarasota&ndash;Venice corridor along US-41, and its hardscape demand skews high-end. The Oaks &mdash; the gated golf-and-country-club enclave behind US-41 &mdash; and the waterfront Southbay Yacht & Racquet Club drive the premium work: travertine and large-format paver pool decks, marble-look surrounds, and sealed paver driveways that hold their finish near the bay. In 34229 communities like Rivendell, Willowbend, and Park Trace, established homes upgrade builder broom-finish driveways to clay and concrete pavers and rebuild aging lanai slabs into proper pool decks. Closer to Little Sarasota Bay along Bay Street and Blackburn Point, salt air makes sealing and proper curing non-negotiable. Across Osprey the work runs from stamped-concrete patios and paver walkways in the wooded inland neighborhoods to luxury travertine pool decks on the water, with HOA architectural review shaping color and pattern in the gated sections.",
        "context_short": "Osprey &mdash; affluent community between Sarasota and Venice on US-41. The Oaks and Southbay Yacht & Racquet Club drive luxury travertine and paver pool decks; Rivendell, Willowbend, and Park Trace homes upgrade driveways to pavers.",
        "humidity_note": "Osprey&rsquo;s bayfront lots along Little Sarasota Bay face salt-air exposure, so sealed pavers, proper concrete cover, and full curing are essential to resist surface scaling and efflorescence.",
        "landmarks": "Historic Spanish Point, Oscar Scherer State Park, the Legacy Trail, Casey Key, Blackburn Point Bridge",
        "primary_market": "Luxury travertine and paver pool decks plus paver driveway upgrades in gated and waterfront communities",
        "trade_class": "Sarasota County permitting; HOA architectural review applies in gated communities such as The Oaks and Southbay Yacht & Racquet Club.",
    },
    "nokomis": {
        "name": "Nokomis",
        "slug": "nokomis",
        "county": "Sarasota County",
        "state": "FL",
        "zips": ["34275"],
        "population": "3,500+ (Greater Nokomis area much larger)",
        "growth": "Rapid new-construction growth 2020&ndash;2025",
        "lat": "27.1208",
        "lng": "-82.4445",
        "neighborhoods": [
            "Calusa Lakes","Sorrento East","Sorrento South","Laurel","Mission Valley",
            "Venice Hills","Bellacina by Casey Key","Vicenza","Toscana Isles","Milano",
            "Talon Preserve","Aria","Sorrento Ranches","Nokomis Beach","Casey Key"
        ],
        "context": "Nokomis straddles US-41 and I-75 just north of Venice, and the rush of new construction east of the interstate has made it one of southern Sarasota County&rsquo;s busiest hardscape markets. Master-planned communities like Bellacina by Casey Key, Toscana Isles, Talon Preserve, and Vicenza deliver builder homes with plain broom-finish driveways and bare lanais, and owners upgrade within a year or two to paver driveways, travertine or paver pool decks, and stamped-concrete entries. In the established 34275 neighborhoods &mdash; Calusa Lakes, Sorrento East and South, Mission Valley &mdash; older homes get fresh poured driveways, paver walkways, and decorative patios. Out toward Nokomis Beach and Casey Key, waterfront and near-coastal slabs face salt air, so sealed pavers and proper curing matter. Paver driveways and pool decks dominate the new gated sections, while decorative and broom-finish concrete carry the inland and coastal renovation work.",
        "context_short": "Nokomis &mdash; coastal Sarasota County community north of Venice with heavy new construction. Bellacina, Toscana Isles, and Talon Preserve drive paver driveway and pool-deck upgrades; Calusa Lakes and Sorrento East get poured-concrete and decorative work.",
        "humidity_note": "Near-coastal Nokomis Beach and Casey Key slabs face salt-air exposure while inland sandy soils shift seasonally, so sealed pavers, proper curing, and compacted sub-base both matter here.",
        "landmarks": "Nokomis Beach, Casey Key, Oscar Scherer State Park, the Legacy Trail, the Venice Jetty",
        "primary_market": "New-construction paver driveways and pool decks east of I-75 plus coastal and inland decorative-concrete work",
        "trade_class": "Sarasota County permitting; HOA architectural review applies in the master-planned communities east of I-75.",
    },
    "arcadia": {
        "name": "Arcadia",
        "slug": "arcadia",
        "county": "DeSoto County",
        "state": "FL",
        "zips": ["34266","34265","34269"],
        "population": "7,800+ city (DeSoto County 35,000+)",
        "growth": "Steady rural growth 2020&ndash;2025",
        "lat": "27.2156",
        "lng": "-81.8584",
        "neighborhoods": [
            "Historic Downtown Arcadia","Antique District","West Oak Street","North Hillsborough Avenue","Brownville",
            "Fort Ogden","Nocatee","Lake Suzy","Hansel","Owens",
            "Pine Level","Southeast Arcadia","Smith-Brown","Magnolia Manor","Villa Margarita"
        ],
        "context": "Arcadia is DeSoto County&rsquo;s seat and the heart of inland ranch-and-citrus country, so its concrete work looks different from the coastal towns. Out on the cattle ranches and groves around Brownville, Fort Ogden, Nocatee, and Pine Level, the demand is for long rural driveways, RV and equipment pads, ag and barn slabs, and well-house and shop floors poured to stand up to heavy loads. In the 34266 core and the historic downtown antique district, the work runs to poured-concrete driveways, sidewalks, and decorative or stamped patios for the older bungalows and storefronts. Lake Suzy, on the southwest edge toward Port Charlotte, adds a more suburban mix of paver driveways and pool decks. With fewer HOAs than the Gulf-coast markets, Arcadia jobs lean practical and durable &mdash; thick, well-jointed slabs and broom-finish or stamped concrete &mdash; though paver and decorative upgrades show up in the newer subdivisions and around Lake Suzy.",
        "context_short": "Arcadia &mdash; rural DeSoto County seat and ranch town with a historic downtown antique district. Long rural driveways, RV and equipment pads, and ag and barn slabs dominate, with poured-concrete and stamped patios downtown and pavers around Lake Suzy.",
        "humidity_note": "Arcadia&rsquo;s inland soils and heavy equipment loads on rural pads demand deep sub-base compaction, thicker slabs, and properly spaced control joints to prevent cracking under load.",
        "landmarks": "Historic Downtown Arcadia, the Arcadia Antique District, the DeSoto County Courthouse, the Arcadia All-Florida Championship Rodeo, the Peace River",
        "primary_market": "Rural ranch driveways, RV and equipment pads, ag and barn slabs plus downtown poured-concrete and decorative flatwork",
        "trade_class": "DeSoto County and City of Arcadia permitting; a downtown historic district overlay applies in the antique district, with few HOAs elsewhere.",
    },
    "anna-maria": {
        "name": "Anna Maria",
        "slug": "anna-maria",
        "county": "Manatee County",
        "state": "FL",
        "zips": ["34216"],
        "population": "1,000+ (seasonal population far higher)",
        "growth": "Stable resident base with strong vacation-rental demand 2020&ndash;2025",
        "lat": "27.5306",
        "lng": "-82.7345",
        "neighborhoods": [
            "Pine Avenue","Bean Point","North Shore","Gulf Drive","Bay Boulevard",
            "Crescent Drive","Willow Avenue","Magnolia Avenue","Palm Avenue","Spring Avenue",
            "Lakeview Drive","City Pier District","Rod & Reel Pier area","South Bay Boulevard","Tarpon Street"
        ],
        "context": "Anna Maria is the northern tip of Anna Maria Island, a barrier-island town of cottages, elevated coastal homes, and a heavy concentration of vacation rentals around Pine Avenue and Bean Point. The hardscape demand here is shaped entirely by salt air and rental turnover: owners want paver driveways and travertine or paver pool decks that look sharp in listing photos and stand up to constant guest traffic, plus elevated and coastal slabs poured to resist scaling near the Gulf. Along Gulf Drive, Bay Boulevard, and the avenues toward the City Pier, older block cottages get fresh poured driveways, paver walkways, and decorative patios as part of remodels and rental conversions. Because nearly every lot sits within yards of saltwater, sealed pavers, corrosion-resistant reinforcement, proper concrete cover, and full curing are essential. Paver driveways and pool decks dominate the vacation-rental upgrades, while decorative concrete covers patios, entries, and walkways.",
        "context_short": "Anna Maria &mdash; barrier-island town at the north end of Anna Maria Island, heavy on vacation rentals around Pine Avenue and Bean Point. Salt-air paver driveways, travertine pool decks, and elevated coastal slabs built for rental durability define the market.",
        "humidity_note": "Every Anna Maria lot sits within yards of the Gulf, so sealed pavers, corrosion-resistant reinforcement, proper concrete cover, and full curing are essential to fight constant salt-air scaling and efflorescence.",
        "landmarks": "Anna Maria City Pier, the Rod & Reel Pier, Bean Point, Pine Avenue, Bayfront Park",
        "primary_market": "Salt-air paver driveways and travertine pool decks for vacation rentals plus elevated coastal slabs and decorative flatwork",
        "trade_class": "City of Anna Maria and Manatee County permitting, with coastal-construction and flood-zone requirements shaping elevated slab and deck work near the Gulf.",
    },
    "longboat-key": {
        "name": "Longboat Key",
        "slug": "longboat-key",
        "county": "Manatee/Sarasota Counties",
        "state": "FL",
        "zips": ["34228"],
        "population": "7,500+ (seasonal population far higher)",
        "growth": "Stable luxury market 2020&ndash;2025",
        "lat": "27.4131",
        "lng": "-82.6587",
        "neighborhoods": [
            "Bay Isles","Country Club Shores","Longboat Key Club","Sleepy Lagoon","Emerald Harbor",
            "Longbeach Village","Sand Cay","Spanish Main Yacht Club","Buttonwood Cove","Corey&rsquo;s Landing",
            "Queens Harbour","Harbour Oaks","Cedars East","Tangerine Bay","Bayport"
        ],
        "context": "Longboat Key is the Gulf-coast luxury barrier island, stretching across the Manatee&ndash;Sarasota county line, and its hardscape market is unapologetically high-end. In Bay Isles, Country Club Shores, the Longboat Key Club, Emerald Harbor, and Sleepy Lagoon, waterfront estates drive premium work: travertine and large-format paver pool decks, marble-look and shellstone surrounds, sealed paver driveways, and salt-tolerant flatwork engineered to survive constant sea spray. Many homes back to the bay or the Gulf, so corrosion-resistant reinforcement, generous concrete cover, and meticulous sealing are the baseline, not an upgrade. In the older Longbeach Village at the north end, cottages get fresh poured driveways, paver walkways, and decorative patios as part of careful remodels. Across the key the demand centers on luxury travertine pool decks and paver driveways, with HOA and club architectural review setting strict standards on color, stone selection, and joint detail.",
        "context_short": "Longboat Key &mdash; luxury Gulf barrier island across two counties. Bay Isles, Country Club Shores, and the Longboat Key Club drive high-end travertine pool decks, marble-look surrounds, and sealed paver driveways built to survive salt spray.",
        "humidity_note": "Longboat Key estates sit feet from the Gulf and bay, so corrosion-resistant reinforcement, generous concrete cover, and meticulous sealing are baseline requirements against relentless salt-air scaling.",
        "landmarks": "the Longboat Key Club, Bayfront Park, Joan M. Durante Park, Longboat Pass Bridge, the Gulf of Mexico beaches",
        "primary_market": "High-end travertine and paver pool decks plus sealed paver driveways on waterfront estates",
        "trade_class": "Town of Longboat Key permitting across Manatee and Sarasota Counties; HOA and club architectural review plus coastal-construction requirements shape the work.",
    },
    "myakka-city": {
        "name": "Myakka City",
        "slug": "myakka-city",
        "county": "Manatee County",
        "state": "FL",
        "zips": ["34251"],
        "population": "1,500+ (rural east Manatee area)",
        "growth": "Slow rural growth 2020&ndash;2025",
        "lat": "27.3553",
        "lng": "-82.1745",
        "neighborhoods": [
            "Myakka City proper","Pomello Park","Oak Knoll","Panther Ridge","Hidden River",
            "Clay Gully","Wauchula Road corridor","Verna","Singletary Road area","Taylor Road area",
            "Crooked River Ranch","Myakka Valley Ranches","Duette","Bethany","Old Myakka"
        ],
        "context": "Myakka City is rural east Manatee County &mdash; equestrian and ranch country spread along SR-70 and SR-64 toward the DeSoto line, where parcels run to acreage and HOAs are scarce. The concrete work here is built for utility: long ranch and acreage driveways that run hundreds of feet from the road, RV pads, equipment and trailer pads, ag and barn slabs, well-house and shop floors, and horse-barn aisles and wash racks poured to take heavy loads and hooves. In the larger-lot communities like Panther Ridge, Pomello Park, and Myakka Valley Ranches, custom homes add paver driveways, pool decks, and decorative or stamped patios to the mix. With few HOAs and big distances, the priority is thick, well-jointed, properly based slabs that hold up under trucks, tractors, and trailers. Broom-finish and structural concrete carry the bulk of the volume, while pavers and decorative finishes show up on the custom-home and pool-deck jobs.",
        "context_short": "Myakka City &mdash; rural equestrian and ranch country in east Manatee County. Long acreage driveways, RV pads, equipment and barn slabs, and horse-barn floors dominate, with paver driveways and pool decks on the larger custom-home lots in Panther Ridge and Myakka Valley Ranches.",
        "humidity_note": "Myakka City&rsquo;s rural slabs carry heavy truck, tractor, and trailer loads, so deep sub-base compaction, thicker pours, and properly spaced control joints are essential to prevent cracking and settling.",
        "landmarks": "Myakka River State Park, Crowley Museum & Nature Center, the Myakka River, Duette Preserve, SR-70 ranch country",
        "primary_market": "Long acreage ranch driveways, RV and equipment pads, ag and barn slabs plus custom-home paver driveways and pool decks",
        "trade_class": "Manatee County permitting; large agricultural parcels and few HOAs mean fewer architectural-review constraints than the coastal markets.",
    },
}
