# Lakewood Ranch Concrete &mdash; service-area city data (part 2 of multi-file CITIES set)
CITIES = {
    "venice": {
        "name": "Venice",
        "slug": "venice",
        "county": "Sarasota County",
        "state": "FL",
        "zips": ["34284","34285","34292","34293"],
        "population": "26,000+ city",
        "growth": "Wellen Park alone has added 15,000+ homes since 2018",
        "lat": "27.0998",
        "lng": "-82.4543",
        "neighborhoods": [
            "Venice Island","Historic Downtown Venice","Venice Gulf View","Venice Beach","Pelican Pointe Golf &amp; Country Club",
            "Venetian Golf &amp; River Club","Venetia","Sawgrass","Stoneybrook at Venice","Wellen Park",
            "IslandWalk at the West Villages","Gran Paradiso","Renaissance at Wellen Park","Ventura Country Club","Capri Isles",
            "Caribbean Bay","Bird Bay","Jacaranda West","Sorrento East","Eagle Trace"
        ],
        "context": "Venice runs two separate concrete markets out of the same ZIP codes. On Venice Island and around Historic Downtown Venice (34285), retirees buy 1950s and 1960s block homes and want cracked, settled driveways torn out and repoured, plus paver entries and screened lanai slabs that match the coastal character. South of US-41 in Wellen Park and the West Villages (34293), more than fifteen thousand new homes since 2018 leave owners upgrading builder-flat slabs into stamped pool decks, travertine-look pavers, and widened driveways the builder never offered. Communities like Gran Paradiso, IslandWalk, and Renaissance at Wellen Park all run ARC review, so paver color and joint patterns have to be submitted before work starts. The sandy barrier-island subgrade and salt air make proper base prep and control joints the difference between a deck that lasts and one that spider-cracks.",
        "context_short": "Venice &mdash; Sarasota County. 26,000 residents. Split market: Venice Island &amp; Historic Downtown driveway tear-outs and lanai pavers, plus Wellen Park / West Villages new-construction pool decks and stamped concrete (15,000+ homes since 2018).",
        "humidity_note": "Venice Island sits on a barrier island where salt air and sandy fill attack rebar and base alike, so we spec fiber-reinforced mixes and deeper compacted base on every coastal pour.",
        "landmarks": "Venice Beach (the Shark Tooth Capital of the World), Venice Pier, Historic Downtown Venice, Wellen Park Downtown, Caspersen Beach, the Venice Theatre, the Venetian Waterway Park",
        "primary_market": "Venice Island driveway tear-outs &amp; lanai pavers plus Wellen Park new-construction pool decks",
        "trade_class": "Sarasota County permitting; Wellen Park communities add their own master-HOA architectural review for paver and stamped-concrete work.",
    },
    "north-port": {
        "name": "North Port",
        "slug": "north-port",
        "county": "Sarasota County",
        "state": "FL",
        "zips": ["34286","34287","34288","34289","34291"],
        "population": "85,000+ city",
        "growth": "One of Florida&rsquo;s fastest-growing cities, with Wellen Park driving thousands of new starts",
        "lat": "27.0442",
        "lng": "-82.2359",
        "neighborhoods": [
            "Wellen Park","West Villages","Bobcat Trail","Heron Creek","Talon Bay",
            "Sabal Trace","Lakeside Plantation","Cedar Grove at the Woodlands","Watercress Cove","The Woodlands",
            "Toledo Blade corridor","Price Boulevard corridor","Warm Mineral Springs","Tropicaire","Duck Key",
            "Cypress Falls at the Woodlands","Villas of Sabal Trace"
        ],
        "context": "North Port is one of the largest and fastest-building cities on the Gulf Coast, and its concrete demand is overwhelmingly new-construction. The Wellen Park and West Villages communities on the city&rsquo;s southwest edge (34293 and 34289) deliver homes weekly, and owners immediately look to extend builder driveways, pour paver lanais, and add stamped pool decks the base price skipped. The older platted-lots core along the Price Boulevard and Toledo Blade corridors (34286, 34287, 34291) is a sea of 1990s and 2000s homes on quarter-acre sandy lots where driveways have settled and cracked, making tear-out-and-repour work steady. North Port&rsquo;s notoriously sandy, fast-draining soil means base compaction is everything &mdash; a slab poured on loose fill telegraphs cracks within a season. Newer subdivisions like Cedar Grove and Watercress Cove run HOA review, while the older grid is largely unrestricted, so we tailor finishes accordingly.",
        "context_short": "North Port &mdash; Sarasota County. 85,000+ residents and climbing fast. Wellen Park / West Villages new-construction pool decks and paver lanais, plus heavy driveway repour work across the older Price Boulevard and Toledo Blade lot grid.",
        "humidity_note": "North Port&rsquo;s deep sandy fill drains fast but compacts poorly, so we over-compact and test the subgrade before any driveway or deck pour to stop settlement cracking.",
        "landmarks": "Warm Mineral Springs, Wellen Park Downtown, the Atlanta Braves CoolToday Park, Myakkahatchee Creek Environmental Park, North Port Aquatic Center, Blue Ridge Park",
        "primary_market": "Wellen Park new-construction pool decks and pavers plus driveway repours across the older platted-lot grid",
        "trade_class": "City of North Port and Sarasota County permitting, with HOA architectural review in the newer Wellen Park and Woodlands communities.",
    },
    "port-charlotte": {
        "name": "Port Charlotte",
        "slug": "port-charlotte",
        "county": "Charlotte County",
        "state": "FL",
        "zips": ["33948","33952","33953","33954","33980","33981"],
        "population": "60,000+ CDP",
        "growth": "Steady retiree-driven growth with rebuilding momentum after Hurricane Ian",
        "lat": "26.9762",
        "lng": "-82.0906",
        "neighborhoods": [
            "Deep Creek","Section 15","Gulf Cove","South Gulf Cove","Port Charlotte Beach",
            "Charlotte Harbor","Murdock","El Jobean","Harbour Heights","Grassy Point",
            "Riverwood","Heritage Oak Park","Sunseekers corridor","Edgewater","Kings Highway corridor",
            "Biscayne Drive waterfront"
        ],
        "context": "Port Charlotte is a sprawling, canal-laced retiree community where concrete work skews heavily toward repair and replacement. Tens of thousands of 1970s and 1980s block homes across Sections 15 and the Murdock grid (33948, 33952) sit on aging driveways and walkways that have cracked, heaved, and lifted with tree roots, so tear-out-and-repour and sidewalk leveling are bread-and-butter jobs. The waterfront canal neighborhoods &mdash; Gulf Cove, South Gulf Cove, and Grassy Point (33981) &mdash; want salt-tolerant paver pool decks and seawall-adjacent slabs that hold up to brackish exposure. Hurricane Ian accelerated a wave of rebuilds, putting fresh driveways, lanais, and pool decks on the schedule countywide. The sandy, high-water-table subgrade common here makes proper base and jointing critical to prevent the slab cracking retirees most often call about.",
        "context_short": "Port Charlotte &mdash; Charlotte County. 60,000+ residents in a canal-home retiree market. Driveway and sidewalk repair across the 1970s&ndash;80s Section 15 and Murdock grid, plus salt-tolerant paver pool decks in Gulf Cove and South Gulf Cove.",
        "humidity_note": "Canal-front lots in Gulf Cove and Grassy Point sit on high water tables with brackish exposure, so we elevate base material and use salt-resistant mixes to keep pool-deck slabs from spalling.",
        "landmarks": "Charlotte Harbor, the Port Charlotte Beach Park, Sunseeker Resort, the Myakka River, Bayshore Live Oak Park, Charlotte Sports Park",
        "primary_market": "Retiree driveway and sidewalk repair plus salt-tolerant canal-home paver pool decks",
        "trade_class": "Charlotte County Community Development handles permitting, with post-Ian wind and flood requirements shaping many waterfront slab pours.",
    },
    "punta-gorda": {
        "name": "Punta Gorda",
        "slug": "punta-gorda",
        "county": "Charlotte County",
        "state": "FL",
        "zips": ["33950","33982","33983"],
        "population": "20,000+ city",
        "growth": "Babcock Ranch master-planned solar town adding thousands of new homes",
        "lat": "26.9298",
        "lng": "-82.0454",
        "neighborhoods": [
            "Punta Gorda Isles","Burnt Store Isles","Babcock Ranch","Deep Creek","Seminole Lakes",
            "Historic Downtown Punta Gorda","Charlotte Park","Pirate Harbor","Trabue","Creekside",
            "Calusa Creek","Founders Square at Babcock Ranch","Lake Babcock","Trails Edge","Burnt Store Marina"
        ],
        "context": "Punta Gorda splits its concrete demand between high-end waterfront and brand-new master-planned construction. Punta Gorda Isles and Burnt Store Isles (33950) are premium sailboat-canal neighborhoods where owners invest in paver pool decks, travertine lanais, and decorative driveways that complement the waterfront homes &mdash; and where brackish canal exposure demands salt-tolerant mixes and elevated base. To the northeast, Babcock Ranch (33982) is a major master-planned solar town pouring driveways, sidewalks, and pool decks on a continuous new-build schedule, with strict ARC standards dictating paver palettes and finishes around Founders Square and Lake Babcock. The Deep Creek and Seminole Lakes deed-restricted communities (33983) add a steady stream of retiree driveway and walkway repairs. Across all of it, sandy subgrade and a high water table make compaction and control-joint placement the deciding factor in whether a slab cracks.",
        "context_short": "Punta Gorda &mdash; Charlotte County. 20,000+ residents. Premium paver pool decks in the Punta Gorda Isles and Burnt Store Isles canals, continuous new-construction at Babcock Ranch, and retiree repair work in Deep Creek and Seminole Lakes.",
        "humidity_note": "Sailboat-canal lots in Punta Gorda Isles and Burnt Store Isles carry brackish water tables, so we elevate base and specify salt-resistant mixes to keep waterfront pool decks from spalling.",
        "landmarks": "Fishermen&rsquo;s Village, the Peace River, Historic Downtown Punta Gorda, Babcock Ranch, Ponce de Leon Park, the Charlotte Harbor Preserve, Burnt Store Marina",
        "primary_market": "Canal-home paver pool decks plus Babcock Ranch new-construction driveways and decks",
        "trade_class": "Charlotte County permitting, with Babcock Ranch enforcing its own town and master-HOA architectural standards on paver and concrete work.",
    },
    "riverview": {
        "name": "Riverview",
        "slug": "riverview",
        "county": "Hillsborough County",
        "state": "FL",
        "zips": ["33569","33578","33579"],
        "population": "100,000+ CDP",
        "growth": "One of Hillsborough County&rsquo;s fastest-growing suburbs, dense with new-build subdivisions",
        "lat": "27.8661",
        "lng": "-82.3265",
        "neighborhoods": [
            "Panther Trace","Summerfield","Lucaya Lake Club","Triple Creek","South Fork",
            "Boyette","Rivercrest","Ventana","Winthrop Village","Bloomingdale Ridge",
            "Shadow Run","Avelar Creek","Medford Lakes","Belmond Reserve","Waterleaf",
            "Riverglen","Lake St. Charles"
        ],
        "context": "Riverview is a booming Hillsborough County bedroom suburb where concrete demand is driven almost entirely by new and recent construction. Sprawling subdivisions like Triple Creek, Lucaya Lake Club, South Fork, and Ventana (33579 and 33578) deliver thousands of production homes, and owners move quickly to extend the standard builder driveway, add paver walkways, and pour stamped or paver pool decks that the base price left off. Established communities like Panther Trace, Summerfield, and Rivercrest (33569) are now fifteen to twenty years old, generating repair-and-replace work on settled driveways and cracked lanai slabs. Most of these subdivisions run HOA and ARC review, so paver colors and patterns require approval before installation. Riverview&rsquo;s sandy, fill-heavy lots make compacted base and proper control joints essential to keep fresh driveways and pool decks from cracking in the first wet season.",
        "context_short": "Riverview &mdash; Hillsborough County. 100,000+ residents in a fast-growing suburb. New-build driveway extensions and paver pool decks across Triple Creek, Ventana, and South Fork, plus repair work in the older Panther Trace and Summerfield communities.",
        "humidity_note": "Riverview&rsquo;s fill-heavy production-home lots settle unevenly, so we compact and verify the subgrade before pouring to keep new driveways and pool decks from cracking in the first rainy season.",
        "landmarks": "the Alafia River, Riverview Civic Center, Triple Creek Nature Preserve, Winthrop Town Centre, the Manatee Viewing Center nearby, Bell Creek Nature Preserve",
        "primary_market": "New-construction driveway extensions and paver pool decks across the production-home subdivisions",
        "trade_class": "Hillsborough County permitting, with HOA and ARC approval required for paver and stamped-concrete work in most Riverview subdivisions.",
    },
    "sun-city-center": {
        "name": "Sun City Center",
        "slug": "sun-city-center",
        "county": "Hillsborough County",
        "state": "FL",
        "zips": ["33573"],
        "population": "25,000+ community",
        "growth": "One of Florida&rsquo;s largest 55+ communities, still expanding with new villages",
        "lat": "27.7159",
        "lng": "-82.3540",
        "neighborhoods": [
            "Kings Point","Sun City Center Core","Renaissance","Caloosa Country Club","Del Webb",
            "Cypress Creek","La Paloma","Greenbriar","Sandpiper","Calusa Point",
            "Lakeside","Verona","Belvedere","Cordoba"
        ],
        "context": "Sun City Center is one of the largest 55+ retirement communities in Florida, and its concrete market reflects that almost entirely. The original core and the gated Kings Point community (33573) are filled with 1980s and 1990s villas and single-family homes on aging driveways, walkways, and screened lanai slabs that have cracked, settled, and lifted &mdash; making driveway and sidewalk repair the dominant request here. Many residents prefer paver overlays and decorative driveway upgrades that add curb appeal and address trip hazards without a full tear-out. Newer Del Webb and Renaissance villages still see new-construction driveway and pool-deck pours. Because the community is heavily deed-restricted, nearly every project runs through community architectural review, with strict standards on paver color and finish. The sandy subgrade and mature tree roots common to these older streets make root-related heaving and slab cracking a constant driver of repair work.",
        "context_short": "Sun City Center &mdash; Hillsborough County. 25,000+ residents in a major 55+ community. Driveway, sidewalk, and lanai repair plus paver overlays across the core and Kings Point, with some new-construction work in the Del Webb and Renaissance villages.",
        "humidity_note": "Mature tree roots and sandy subgrade on the older Sun City Center streets heave and crack aging driveways, so we address root intrusion and re-base before repouring or laying pavers.",
        "landmarks": "Kings Point, the Sun City Center golf-cart trail network, Cypress Creek Golf Club, Freedom Plaza, the SCC Community Hall, Little Manatee River nearby",
        "primary_market": "Retiree driveway and sidewalk repair plus paver overlays in a 55+ community",
        "trade_class": "Hillsborough County permitting, with mandatory community architectural review governing paver color and finish across the deed-restricted villages.",
    },
}