# Lakewood Ranch Concrete &mdash; city data (part 1 of 2)
CITIES = {
    "lakewood-ranch": {
        "name": "Lakewood Ranch",
        "slug": "lakewood-ranch",
        "county": "Manatee/Sarasota Counties",
        "state": "FL",
        "zips": ["34202","34211","34212","34240","34238"],
        "population": "60,000+ across 30+ villages",
        "growth": "#1 best-selling master-planned community in the US (eight years running, RCLCO Real Estate Advisors)",
        "lat": "27.4181",
        "lng": "-82.3884",
        "neighborhoods": [
            "Country Club East at Lakewood Ranch","Lakewood Ranch Country Club","The Lake Club","Esplanade Golf & Country Club","Polo Run",
            "Indigo","Mallory Park","Greenbrook","Summerfield","Edgewater Village",
            "Lorraine Lakes","Del Webb Lakewood Ranch","Cresswind Lakewood Ranch","Star Farms at Lakewood Ranch","Sweetwater at Lakewood Ranch",
            "Waterside Place","Azario Esplanade","Avanti at Waterside","Solera at Lakewood Ranch","Savanna at Lakewood Ranch"
        ],
        "context": "Lakewood Ranch is the busiest hardscape market on Florida&rsquo;s Gulf Coast &mdash; thirty thousand acres of master-planned villages straddling the Manatee&ndash;Sarasota line, where almost every new home ships with a builder-poured broom-finish driveway and a screened lanai begging for a real pool deck. In the 34211 ZIP (Polo Run, Indigo, Mallory Park, Lorraine Lakes) and north of SR-64 (Star Farms, Sweetwater, Azario), owners close on builder-original concrete and within a year want paver driveways, travertine pool decks, and stamped or stained patios with character the builder never offered. Demand here splits cleanly: paver driveways and pool decks dominate the gated golf villages like Country Club East and The Lake Club, while broom-finish and decorative concrete flatwork carry the volume builds. Every village runs an HOA architectural review committee, so color, joint pattern, and border details have to clear the ARC before a saw ever cuts.",
        "context_short": "Lakewood Ranch &mdash; 30,000-acre master-planned community across two counties with 30+ villages. New-construction driveways, lanai pool decks, and paver upgrades drive constant hardscape demand, all gated by HOA architectural review.",
        "humidity_note": "Lakewood Ranch sits on sandy, expansive soils with a high rainy-season water table, so control joints and proper sub-base compaction are critical to keep slabs from cracking as the ground swells and shrinks.",
        "landmarks": "Main Street at Lakewood Ranch, Waterside Place, University Town Center (UTC), Premier Sports Campus, Lakewood Ranch Medical Center",
        "primary_market": "New-construction paver driveways & pool decks in master-planned communities",
        "trade_class": "Crosses both Manatee and Sarasota County permitting; HOA architectural review applies in virtually every gated village.",
    },
    "bradenton": {
        "name": "Bradenton",
        "slug": "bradenton",
        "county": "Manatee County",
        "state": "FL",
        "zips": ["34201","34202","34203","34205","34207","34208","34209","34210","34211","34212"],
        "population": "60,000+ city · 420,000+ metro",
        "growth": "12% population growth 2020–2025",
        "lat": "27.4989",
        "lng": "-82.5748",
        "neighborhoods": [
            "Heritage Harbour","River Strand","GreyHawk Landing","Mill Creek","Stoneybrook at Heritage Harbour",
            "Tara Preserve","Country Club East","Esplanade Golf & Country Club","River Wilderness","Rosedale Golf & Country Club",
            "Braden Woods","Cortez","Palma Sola","West Bradenton","River Place",
            "Anna Maria Island","Holmes Beach","Bradenton Beach","Perico Bay","University Park"
        ],
        "context": "Bradenton is Manatee&rsquo;s county seat and our home base, and its split personality drives two very different hardscape markets. East of I-75 along the SR-70 and SR-64 corridors (34212), gated golf communities like Heritage Harbour, GreyHawk Landing, and River Strand are full of newer homes where owners trade builder broom-finish driveways for clay or concrete pavers and rebuild tired lanai slabs into travertine pool decks. West of US-41, the 1960s block homes around Palma Sola and West Bradenton are getting fresh poured driveways, decorative-concrete patios, and paver walkways as younger buyers renovate. Coastal pockets toward Cortez and the island approaches add a salt-air dimension &mdash; sealed pavers and properly cured slabs hold up far better near the water. Whether it&rsquo;s a stamped concrete patio off a ranch or a full paver driveway in a gated village, the work here ranges across the full hardscape spectrum.",
        "context_short": "Bradenton &mdash; Manatee County seat. 60,000 in the city, 420,000 in the metro. Gated golf communities east of I-75 want paver driveways and pool decks; mid-century homes west of US-41 drive poured-concrete and decorative flatwork.",
        "humidity_note": "Summer afternoon downpours and high humidity slow concrete curing, so we schedule pours around the rain and protect fresh slabs to avoid surface crazing and weak finishes.",
        "landmarks": "LECOM Park, IMG Academy, Riverwalk Bradenton, the De Soto Bridge, Robinson Preserve, the Village of the Arts",
        "primary_market": "Paver driveways and lanai pool decks in east-side gated communities plus poured-concrete flatwork in west-side renovations",
        "trade_class": "Manatee County Building & Development permitting; HOA architectural review applies in the east-side gated communities.",
    },
    "parrish": {
        "name": "Parrish",
        "slug": "parrish",
        "county": "Manatee County",
        "state": "FL",
        "zips": ["34219"],
        "population": "28,000+ (doubled since 2015)",
        "growth": "Roughly 100% population growth 2015–2025",
        "lat": "27.5764",
        "lng": "-82.4234",
        "neighborhoods": [
            "North River Ranch","Star Farms at Parrish","Aviary at Rutland Ranch","Crosscreek","Forest Creek",
            "Silverleaf","Twin Rivers","Foxbrook","Canoe Creek","Parrish Lakes",
            "Rye Crossings","Wilderness Reserve","Salt Meadows","Jacaranda Estates","Copperstone"
        ],
        "context": "Parrish is northeastern Manatee County&rsquo;s relocation magnet &mdash; a stretch of US-301 and Moccasin Wallow Road that went from cattle pasture to twenty-eight thousand residents in a decade, and almost all of that growth is brand-new construction. North River Ranch is platted for more than seven thousand homes; Aviary at Rutland Ranch, Canoe Creek, and Salt Meadows are running early phases. That means nearly every hardscape job here starts the same way: a homeowner closes on a builder home with a plain broom-finish driveway and a bare lanai, then upgrades to a paver driveway, a travertine or paver pool deck, and a stamped-concrete entry. Paver work dominates the gated sections, while decorative and broom-finish concrete carries the rest. Inland of US-301, the sandy soils still move with the seasons, so sub-base prep and control joints matter as much in Parrish as anywhere in the county.",
        "context_short": "Parrish &mdash; the fastest-growing community in Manatee County, population doubled since 2015 to 28,000+. New-construction master-planned neighborhoods (North River Ranch, Aviary, Canoe Creek) drive paver driveway and pool-deck upgrades off builder-grade concrete.",
        "humidity_note": "Parrish&rsquo;s sandy inland soils expand and contract with the wet and dry seasons, so deep sub-base compaction and properly spaced control joints are what keep new driveways and slabs from cracking.",
        "landmarks": "Fort Hamer Park, the Fort Hamer Bridge, Florida Railroad Museum, Carlton Reserve trails, Buffalo Creek Park",
        "primary_market": "New-construction paver driveway and pool-deck upgrades off builder-grade concrete",
        "trade_class": "Manatee County permitting; HOA architectural review applies in the master-planned communities.",
    },
    "palmetto": {
        "name": "Palmetto",
        "slug": "palmetto",
        "county": "Manatee County",
        "state": "FL",
        "zips": ["34220","34221"],
        "population": "13,500+ city",
        "growth": "23% growth 2020–2025 (US Census ACS)",
        "lat": "27.5214",
        "lng": "-82.5723",
        "neighborhoods": [
            "Historic Downtown Palmetto","Riviera Dunes","Snead Island","Terra Ceia","Sanctuary Cove",
            "Heron Creek","Esplanade at Artisan Lakes","Artisan Lakes","Trevesta","Northshore at Riviera Dunes",
            "Rye Wilderness Estates","Palmetto Estates","Palm View","Memphis","Ellenton"
        ],
        "context": "Palmetto sits on the north bank of the Manatee River, directly across the De Soto Bridge from downtown Bradenton, and its hardscape market spans old and new. Along the historic waterfront and Snead Island, 1950s through 1970s homes &mdash; many owned by snowbirds &mdash; get new poured driveways, paver walkways, and decorative patios as part of slow restorations, with salt air making proper sealing and curing essential near the water. On the east side along US-301, Artisan Lakes and Trevesta absorb spillover from the Lakewood Ranch boom, delivering builder homes whose owners upgrade to paver driveways and pool decks within the first couple of years. The Riviera Dunes and Northshore neighborhoods add a marina-side mix of patios and pool surrounds. Across both halves of the city, the demand leans toward pavers for driveways and pool decks and decorative concrete for patios and entries.",
        "context_short": "Palmetto &mdash; historic riverfront city across the Manatee River from Bradenton, 13,500 residents. 1950s&ndash;70s waterfront homes get poured driveways and paver walkways; Artisan Lakes and Trevesta along US-301 drive new-construction paver upgrades.",
        "humidity_note": "Waterfront and Snead Island slabs face salt-air exposure, so we use proper concrete cover, sealed pavers, and full curing to resist surface scaling and efflorescence near the river.",
        "landmarks": "Riviera Dunes Marina, Snead Island Causeway, Emerson Point Preserve, the De Soto Bridge, Sutton Park, the Manatee River",
        "primary_market": "Paver driveways and pool decks in Artisan Lakes new builds plus poured-concrete restoration work on the waterfront",
        "trade_class": "Manatee County permitting; downtown historic overlay applies on Riverside Drive and HOA review applies in the US-301 communities.",
    },
    "ellenton": {
        "name": "Ellenton",
        "slug": "ellenton",
        "county": "Manatee County",
        "state": "FL",
        "zips": ["34222"],
        "population": "5,000+ (Greater Ellenton/North River area much larger)",
        "growth": "Steady growth driven by North River-area development 2020–2025",
        "lat": "27.5222",
        "lng": "-82.5279",
        "neighborhoods": [
            "Covered Bridge Estates","Bougainvillea Place","North River","Foxbrook","Old Mill",
            "Oak Run","Magnolia Manor","Ellenton Gardens","Willow Walk","Gillette",
            "Hidden Oaks","Northwood Park","River Place at Ellenton","Sugar Mill Lakes","Terra Ceia Village"
        ],
        "context": "Ellenton is a small Manatee County community just north of the Manatee River along I-75, best known for the Ellenton Premium Outlets and the historic Gamble Plantation, but it anchors a growing residential band of master-planned and established neighborhoods. Covered Bridge Estates and Bougainvillea Place are full of homes whose owners upgrade plain builder driveways to clay and concrete pavers and rebuild lanai slabs into proper pool decks, while the older sections around Old Mill and Gillette generate poured-concrete driveways, decorative patios, and paver walkways. The North River and Foxbrook areas nearby push newer construction that follows the same pattern: builder broom-finish concrete replaced or fronted with pavers within a year or two of closing. With the outlets and US-301 traffic, durable, well-jointed flatwork matters here, and pavers dominate the driveway and pool-deck demand while stamped and broom-finish concrete cover patios and approaches.",
        "context_short": "Ellenton &mdash; small Manatee County community near the Ellenton Premium Outlets and Gamble Plantation. Covered Bridge, Bougainvillea Place, and nearby North River neighborhoods drive paver driveway and pool-deck upgrades plus poured-concrete patio work.",
        "humidity_note": "Ellenton&rsquo;s sandy soils near the Manatee River shift with seasonal moisture, so compacted sub-base and properly spaced control joints are essential to prevent driveway and slab cracking.",
        "landmarks": "Ellenton Premium Outlets, Gamble Plantation Historic State Park, the Manatee River, Fort Hamer area, Buffalo Creek Park",
        "primary_market": "Paver driveways and pool decks in master-planned neighborhoods plus poured-concrete flatwork in established sections",
        "trade_class": "Manatee County permitting; HOA architectural review applies in communities such as Covered Bridge Estates and Bougainvillea Place.",
    },
    "sarasota": {
        "name": "Sarasota",
        "slug": "sarasota",
        "county": "Sarasota County",
        "state": "FL",
        "zips": ["34230","34231","34232","34233","34234","34235","34236","34237","34238","34239","34240","34241","34242","34243"],
        "population": "58,000+ city · 450,000+ metro",
        "growth": "Median home price up 64% since 2020 (Sarasota-Manatee MLS)",
        "lat": "27.3364",
        "lng": "-82.5307",
        "neighborhoods": [
            "Downtown Sarasota","St. Armands Key","Lido Key","Siesta Key","Longboat Key",
            "Bird Key","Bay Isles","Golden Gate Point","The Meadows","Palmer Ranch",
            "Gulf Gate","Laurel Park","Southside Village","Cherokee Park","Indian Beach",
            "Sapphire Shores","Arlington Park","University Park (Sarasota side)","Hidden Lake","The Landings",
            "Oakford"
        ],
        "context": "Sarasota is the cultural anchor of the Suncoast, and its hardscape market is as bifurcated as its real estate. On the keys &mdash; Siesta, Lido, Longboat, Bird, and Casey &mdash; waterfront homes drive the high end, where owners want travertine and large-format paver pool decks, marble-look and shellstone surrounds, and salt-tolerant flatwork built to survive constant sea spray. West-of-Trail neighborhoods like Southside Village and Cherokee Park hold restored 1950s ranch homes getting fresh poured driveways, paver walkways, and stamped or stained concrete patios. East of I-75, Palmer Ranch and The Meadows give a steady stream of mid-2000s homes upgrading builder driveways and lanai slabs to pavers. Across the city the work runs the full range: premium paver pool decks near the water, decorative concrete patios in the inland renovations, and paver driveways everywhere in between &mdash; with salt air making sealing and proper curing non-negotiable on the keys.",
        "context_short": "Sarasota &mdash; Suncoast cultural anchor, 58,000 in the city and 450,000 in the metro. Keys waterfront homes drive premium paver pool decks; west-of-Trail ranches and Palmer Ranch homes drive driveway and decorative-concrete work.",
        "humidity_note": "Siesta Key and Lido Key slabs sit feet from saltwater, so corrosion-resistant reinforcement, proper concrete cover, and sealed pavers are essential to fight salt-air scaling and efflorescence.",
        "landmarks": "Siesta Key Beach (rated #1 beach in America by Dr. Beach multiple years), the John & Mable Ringling Museum of Art, St. Armands Circle, the Sarasota Opera House, Marie Selby Botanical Gardens, the Van Wezel Performing Arts Hall",
        "primary_market": "Premium paver pool decks on the keys plus paver driveways and decorative-concrete patios inland",
        "trade_class": "Sarasota County and City of Sarasota permitting; salt-air exposure on the keys and HOA review in gated communities both shape the work.",
    },
}
