# Lakewood Ranch Concrete &mdash; city data (part 3 of 3)
CITIES = {
    "tampa": {
        "name": "Tampa",
        "slug": "tampa",
        "county": "Hillsborough County",
        "state": "FL",
        "zips": ["33602","33603","33604","33605","33606","33609","33611","33612","33613","33614","33615","33616","33618","33619","33624","33625","33626","33629","33634","33647"],
        "population": "400,000+ city · 1.5M+ Hillsborough County",
        "growth": "Strongest five-year job growth of any major Florida metro (BLS)",
        "lat": "27.9506",
        "lng": "-82.4572",
        "neighborhoods": [
            "Hyde Park","Davis Islands","Bayshore Beautiful","South Tampa","Channelside",
            "Westshore","Carrollwood","New Tampa","Tampa Palms","Westchase",
            "Town N&rsquo; Country","Seminole Heights","Ybor City","Beach Park","Sunset Park",
            "Culbreath Heights","Palma Ceia","Bayshore Gardens","Hunters Green","Arbor Greene"
        ],
        "context": "Tampa is the largest city in our service area and its hardscape work splits sharply by neighborhood. In South Tampa &mdash; Hyde Park, Palma Ceia, Beach Park, Sunset Park, and Bayshore Beautiful (33606, 33609, 33629) &mdash; owners of restored 1920s bungalows and teardown-rebuild luxury homes want paver driveways, travertine pool decks, and stamped-concrete entries with real detail. Davis Islands and the Bayshore waterfront add canal-side pool surrounds where salt air and seawall proximity make sealed pavers and properly cured slabs essential. North and east &mdash; New Tampa, Tampa Palms, Arbor Greene, and Hunters Green (33647) &mdash; gated golf communities run on builder broom-finish concrete that owners upgrade to paver driveways and lanai pool decks, all subject to HOA architectural review. Carrollwood and Westchase fill in steady decorative-concrete patio and paver-walkway demand across mid-1990s and 2000s homes.",
        "context_short": "Tampa &mdash; 400,000 in the city, 1.5M in Hillsborough County. South Tampa bungalows and luxury rebuilds drive paver driveways and pool decks; New Tampa and Tampa Palms gated communities drive builder-concrete upgrades under HOA review.",
        "humidity_note": "Tampa&rsquo;s daily summer thunderstorms and high humidity slow concrete curing, so we time pours around afternoon rain and protect fresh slabs to prevent surface crazing and weak finishes.",
        "landmarks": "Bayshore Boulevard, the Tampa Riverwalk, Amalie Arena, Raymond James Stadium, Ybor City, the University of Tampa, Busch Gardens",
        "primary_market": "Paver driveways and pool decks in South Tampa rebuilds plus builder-concrete upgrades in north-side gated communities",
        "trade_class": "City of Tampa and Hillsborough County permitting; historic district review applies in Hyde Park and HOA architectural review applies in the gated communities.",
    },
    "st-petersburg": {
        "name": "St. Petersburg",
        "slug": "st-petersburg",
        "county": "Pinellas County",
        "state": "FL",
        "zips": ["33701","33702","33703","33704","33705","33706","33707","33708","33709","33710","33711","33712","33713","33714","33715","33716"],
        "population": "260,000+ city · 1M+ Pinellas County",
        "growth": "Highest median rent growth in the Tampa Bay MSA 2020&ndash;2024 (Zillow)",
        "lat": "27.7676",
        "lng": "-82.6403",
        "neighborhoods": [
            "Downtown St. Petersburg","Snell Isle","Old Northeast","Coffee Pot Bayou","Crescent Lake",
            "Crescent Heights","Shore Acres","Bayway Isles","Pasadena","Tierra Verde",
            "Allendale","Disston Heights","Historic Kenwood","Euclid&ndash;St. Paul","Driftwood",
            "Riviera Bay","Gulfport (border)","Old Southeast","Bayou Bonita","Pinellas Point"
        ],
        "context": "St. Petersburg is the oldest and most architecturally varied city we serve, and its hardscape practice leans heavily toward renovation and waterfront work. In the historic neighborhoods &mdash; Old Northeast, Historic Kenwood, Crescent Heights, and Snell Isle (33701, 33704) &mdash; 1920s bungalows and Mediterranean Revival homes get paver driveways, decorative-concrete walkways, and restored patios that have to fit older streetscapes. The waterfront and island sections &mdash; Snell Isle, Bayway Isles, Tierra Verde, and Shore Acres &mdash; bring canal-side and bayfront pool decks where salt air, seawalls, and a high water table demand sealed pavers, proper concrete cover, and full curing to resist scaling and efflorescence. Inland through Disston Heights and Pinellas Point, mid-century block homes drive poured driveways, stamped patios, and paver upgrades. Old slabs and tight lots make demolition, sub-base prep, and access planning as important as the finish itself.",
        "context_short": "St. Petersburg &mdash; Pinellas County, 260,000 in the city and 1M+ countywide. Historic bungalow neighborhoods drive paver driveways and decorative walkways; Snell Isle, Tierra Verde, and Shore Acres drive salt-tough canal-side pool decks.",
        "humidity_note": "St. Pete&rsquo;s island and canal-side slabs sit close to saltwater and a high water table, so sealed pavers, proper concrete cover, and full curing are essential to fight salt-air scaling and efflorescence.",
        "landmarks": "The Salvador Dal&iacute; Museum, the St. Pete Pier, Tropicana Field, Sunken Gardens, the Vinoy Park Hotel, North Straub Park",
        "primary_market": "Paver driveways and decorative walkways in historic neighborhoods plus salt-tough canal-side pool decks on the islands",
        "trade_class": "Pinellas County and City of St. Petersburg permitting; historic preservation review applies in Old Northeast, Kenwood, and similar districts.",
    },
    "brandon": {
        "name": "Brandon",
        "slug": "brandon",
        "county": "Hillsborough County",
        "state": "FL",
        "zips": ["33510","33511"],
        "population": "115,000+ (census-designated place)",
        "growth": "Steady suburban growth across east Hillsborough 2020&ndash;2025",
        "lat": "27.9378",
        "lng": "-82.2859",
        "neighborhoods": [
            "Bloomingdale","Brandon","Limona","Lakewood Ridge","Providence Lakes",
            "Heather Lakes","Sterling Ranch","Brentwood Hills","Hickory Lakes","Lakeview Village",
            "Crosby Crossings","Peppermill","Four Winds Estates","Kings Lake","Magnolia Park",
            "Buckhorn","Lake Brandon","Lithia Pinecrest corridor"
        ],
        "context": "Brandon is east Hillsborough&rsquo;s established suburban core, just off I-75 and SR-60, and its hardscape work is mostly renovation of 1980s through early-2000s subdivisions. In Bloomingdale, Brentwood Hills, and the Lithia Pinecrest corridor (33511), original broom-finish driveways and tired lanai slabs get rebuilt as paver driveways and travertine or paver pool decks, while owners add stamped-concrete patios and paver walkways to update aging backyards. Providence Lakes, Heather Lakes, and Lakewood Ridge (33510) carry steady demand for decorative concrete and driveway resurfacing as homes turn over to younger buyers. Historic Limona holds older lots where poured driveways and walkways come with mature-tree and access challenges. Many Brandon subdivisions run an HOA architectural review committee, so paver color, border detail, and joint pattern have to clear the ARC before work starts.",
        "context_short": "Brandon &mdash; established east Hillsborough suburb of 115,000+. 1980s&ndash;2000s subdivisions like Bloomingdale, Providence Lakes, and Heather Lakes drive paver driveway and pool-deck rebuilds plus decorative-concrete patio work, much of it under HOA review.",
        "humidity_note": "Brandon&rsquo;s sandy soils shift with the wet and dry seasons, so deep sub-base compaction and properly spaced control joints are what keep rebuilt driveways and slabs from cracking.",
        "landmarks": "Westfield Brandon mall, the Brandon Regional Hospital, Bloomingdale Golfers Club, Alafia River, the SR-60 corridor",
        "primary_market": "Paver driveway and pool-deck rebuilds plus decorative-concrete patios in established subdivisions",
        "trade_class": "Hillsborough County permitting; HOA architectural review applies in subdivisions such as Bloomingdale, Providence Lakes, and Heather Lakes.",
    },
    "ruskin": {
        "name": "Ruskin",
        "slug": "ruskin",
        "county": "Hillsborough County",
        "state": "FL",
        "zips": ["33570","33573"],
        "population": "40,000+ (rapidly growing SouthShore area)",
        "growth": "Among the fastest-growing communities in south Hillsborough 2020&ndash;2025",
        "lat": "27.7206",
        "lng": "-82.4334",
        "neighborhoods": [
            "Little Harbor","Cypress Creek","Hawks Point","Bahia Lakes","Shell Point",
            "Mira Lago","Brookside Estates","Belmont","River Bend","Spencer Creek",
            "Wellington North","Antigua Cove","Ruskin Reserve","Hawkstone","Sandpiper Point"
        ],
        "context": "Ruskin anchors the SouthShore growth band along US-41 and I-75, where former farmland has filled with master-planned subdivisions and waterfront pockets near the Little Manatee River and Tampa Bay. Almost all of the volume here is new construction: homeowners close on builder broom-finish driveways and bare lanais in Belmont, Cypress Creek, Bahia Lakes, and Spencer Creek (33573), then upgrade to paver driveways, paver and travertine pool decks, and stamped-concrete entries within a year or two. Waterfront sections like Little Harbor and Shell Point (33570) add canal- and bay-side pool decks where salt air calls for sealed pavers and well-cured slabs. Hawks Point and Mira Lago round out the gated demand. Paver work dominates the driveway and pool-deck market while decorative and broom-finish concrete carry patios and approaches, with HOA architectural review standard across the master-planned communities.",
        "context_short": "Ruskin &mdash; fast-growing SouthShore community of 40,000+ on US-41 and I-75. New-construction subdivisions like Belmont, Cypress Creek, and Bahia Lakes drive paver driveway and pool-deck upgrades; Little Harbor and Shell Point add canal-side decks.",
        "humidity_note": "Ruskin&rsquo;s low-lying sandy soils sit near a high water table close to the bay, so deep sub-base compaction and proper control joints are essential to keep new driveways and pool decks from cracking and settling.",
        "landmarks": "Little Harbor, E.G. Simmons Conservation Park, the Little Manatee River, Ruskin Family Drive-In, the SouthShore Bay area",
        "primary_market": "New-construction paver driveways and pool decks in SouthShore master-planned communities",
        "trade_class": "Hillsborough County permitting; HOA architectural review applies across the SouthShore master-planned communities.",
    },
    "wimauma": {
        "name": "Wimauma",
        "slug": "wimauma",
        "county": "Hillsborough County",
        "state": "FL",
        "zips": ["33598"],
        "population": "12,000+ (rapidly expanding with new master-planned communities)",
        "growth": "Explosive new-construction growth in south Hillsborough 2020&ndash;2025",
        "lat": "27.7142",
        "lng": "-82.2992",
        "neighborhoods": [
            "Ayersworth Glen","Sereno","Southshore Bay","Southshore Bay Lagoon","Berry Bay",
            "Valencia Lakes","Valencia del Sol","DG Farms","Vista Palms","Dakota Ridge",
            "Forest Brooke","Highland Estates","Cordoba Ranch (south)","Medley at Southshore Bay","Creek Preserve"
        ],
        "context": "Wimauma has gone from rural farmland to one of south Hillsborough&rsquo;s busiest new-construction markets, driven by master-planned and 55-plus communities along SR-674 and US-301 (33598). Valencia Lakes and Valencia del Sol bring active-adult homes whose owners upgrade builder driveways to pavers and rebuild lanais into paver and travertine pool decks. Southshore Bay &mdash; built around a Crystal Lagoon &mdash; along with Berry Bay, Sereno, Ayersworth Glen, and DG Farms (Vista Palms, Forest Brooke) deliver a steady stream of new homes that close on plain broom-finish concrete and add paver driveways, pool decks, and stamped-concrete patios within the first couple of years. Lagoon-adjacent decks call for sealed pavers and careful curing. Paver work dominates the driveway and pool-deck demand while decorative concrete covers patios and entries, and HOA architectural review applies across nearly every community.",
        "context_short": "Wimauma &mdash; rural land turned new-construction hub of 12,000+ in south Hillsborough. Valencia Lakes, Southshore Bay, Berry Bay, and DG Farms drive paver driveway and pool-deck upgrades off builder-grade concrete, all under HOA review.",
        "humidity_note": "Wimauma&rsquo;s sandy inland soils expand and contract between the wet and dry seasons, so deep sub-base compaction and properly spaced control joints are essential to prevent new driveways and slabs from cracking.",
        "landmarks": "Southshore Bay Lagoon, the Valencia Lakes community, Little Manatee River State Park, SR-674 (Sun City Center Boulevard), US-301",
        "primary_market": "New-construction paver driveways and pool decks in master-planned and active-adult communities",
        "trade_class": "Hillsborough County permitting; HOA architectural review applies across communities such as Valencia Lakes, Southshore Bay, and Berry Bay.",
    },
    "apollo-beach": {
        "name": "Apollo Beach",
        "slug": "apollo-beach",
        "county": "Hillsborough County",
        "state": "FL",
        "zips": ["33572"],
        "population": "30,000+ (waterfront SouthShore community)",
        "growth": "Strong waterfront and master-planned growth in south Hillsborough 2020&ndash;2025",
        "lat": "27.7731",
        "lng": "-82.4076",
        "neighborhoods": [
            "MiraBay","Waterset","Symphony Isles","Andalucia","Covington Key",
            "Apollo Beach Golf &amp; Sea Club","Bal Harbour","Cobia Cay","Caloosa Yacht &amp; Racquet Club","Harbour Isles",
            "Southshore Falls","Lago del Mar","Golf and Sea Village","Bimini Bay","Sabal Key"
        ],
        "context": "Apollo Beach is the waterfront heart of SouthShore, a network of canals and lagoon communities off Tampa Bay where pool decks are the headline hardscape. In the gated waterfront sections &mdash; MiraBay, Symphony Isles, Andalucia, Covington Key, and Bal Harbour (33572) &mdash; canal-front homes drive premium paver and travertine pool decks, dock-side patios, and seawall-adjacent flatwork where salt air and tidal exposure make sealed pavers, proper concrete cover, and full curing non-negotiable. Master-planned Waterset and Harbour Isles bring large numbers of newer homes that upgrade builder broom-finish driveways to pavers and rebuild lanais into proper pool decks. Southshore Falls adds active-adult demand for paver driveways and decorative patios. Across the community, paver work dominates driveways and pool decks while stamped and broom-finish concrete cover entries and walkways, and HOA architectural review applies in nearly every gated and master-planned section.",
        "context_short": "Apollo Beach &mdash; waterfront SouthShore community of 30,000+ built on Tampa Bay canals. MiraBay, Symphony Isles, and Andalucia drive premium canal-side paver pool decks; Waterset and Harbour Isles drive new-construction driveway and pool-deck upgrades.",
        "humidity_note": "Apollo Beach&rsquo;s canal-front lots sit feet from saltwater and a tidal water table, so sealed pavers, proper concrete cover, and full curing are essential to resist salt-air scaling and efflorescence.",
        "landmarks": "MiraBay, the Apollo Beach Nature Preserve, Manatee Viewing Center, Apollo Beach Golf &amp; Sea Club, Tampa Bay",
        "primary_market": "Premium canal-side paver pool decks plus new-construction driveway and pool-deck upgrades in master-planned communities",
        "trade_class": "Hillsborough County permitting; salt-air and canal exposure shape the work and HOA architectural review applies in the gated waterfront communities.",
    },
}
