# Lakewood Ranch Concrete — service data, part 3 (paver hardscape)
SERVICES = {
    "paver-driveways": {
        "name": "Paver Driveways",
        "slug": "paver-driveways",
        "short": "Paver Driveways",
        "h1_phrase": "Paver Driveways",
        "card_image": "card-paver-driveways.webp",
        "icon": "07",
        "intro_lead": "Interlocking brick and concrete paver driveways &mdash; engineered base, sand-set field, and locked joints built to carry Florida vehicle loads without rutting, settling, or washing out.",
        "intro_long_p1": "A paver driveway lives or dies on what you never see, and on the Gulf Coast that means the base. The <strong>sandy, fine-grained soil</strong> under most Bradenton, Lakewood Ranch, and Sarasota properties drains fast but holds almost nothing in place, so a driveway dropped onto raw sand will rut under the first loaded truck and pond after the first afternoon storm. We excavate to grade and build a <strong>compacted crushed-limerock base</strong> &mdash; deeper for the driveway than for any patio &mdash; compacting in lifts so the structure carries weight instead of chasing it. The other Florida realities are <strong>drainage and the joints</strong>: we pitch the field to move water off the slab and toward daylight, and we lock the joints with <strong>polymeric sand</strong> so weeds and the ant colonies that love loose joint sand can&rsquo;t take hold. Every driveway runs through our <strong>Lakewood Ranch Concrete 42-Point Install Standard</strong>, and in the deed-restricted villages of Lakewood Ranch we build to <strong>HOA / ARC-approved</strong> color and pattern specs so your install passes review the first time. Estimates are free and financing is available.",
        "intro_long_p2": "We set three families of paver. <strong>Brick pavers</strong> &mdash; true clay, color-fast through decades of Gulf sun &mdash; never fade the way pigmented units can. <strong>Concrete pavers</strong> give you the widest range of shapes, tumbled textures, and tones at the best price, and <strong>permeable pavers</strong> use open joints over an open-graded stone reservoir to let stormwater pass straight through, which matters on lots with tight drainage or coverage limits. Driveway-rated units run thicker &mdash; we set <strong>60&ndash;80 mm</strong> pavers over a base typically <strong>8&ndash;12&Prime; deep</strong> after compaction, versus the lighter section a walkway needs. The whole field gets a <strong>concrete or spiked edge restraint</strong> locked along every open edge, because pavers spread and the perimeter is always the first thing to go without it. We finish with polymeric sand swept and set into the joints, and we&rsquo;ll walk you honestly through <strong>sealing</strong> &mdash; what it does for color and stain resistance, what it costs to maintain, and when it&rsquo;s genuinely worth skipping.",
        "scope_items": [
            "Site excavation &amp; grade staking",
            "Compacted crushed-limerock base in lifts",
            "Geotextile fabric over soft or sandy subgrade",
            "Brick (clay) paver driveways",
            "Concrete paver driveways",
            "Permeable paver driveways with stone reservoir",
            "60&ndash;80 mm driveway-rated paver units",
            "Herringbone, basketweave &amp; running-bond patterns",
            "Soldier-course &amp; contrasting paver borders",
            "Concrete &amp; spiked edge restraints",
            "Drainage pitch &amp; surface grading to daylight",
            "Polymeric-sand joint locking",
            "Apron &amp; garage-threshold transitions",
            "Paver sealing (penetrating &amp; film-forming options)",
            "Old driveway removal &amp; haul-away",
        ],
        "pricing_rows": [
            ("Concrete Paver Driveway (standard)", "$15&ndash;$22/sq ft installed", "Most-installed driveway tier"),
            ("Brick (Clay) Paver Driveway", "$18&ndash;$26/sq ft installed", "Color-fast, premium look"),
            ("Premium / Tumbled Concrete Paver", "$20&ndash;$28/sq ft installed", "Old-world texture &amp; blends"),
            ("Permeable Paver Driveway", "$22&ndash;$30/sq ft installed", "Open joints + deep stone reservoir"),
            ("Heavy-Section Base Upgrade", "+$3&ndash;$6/sq ft", "Soft subgrade or RV / boat loads"),
            ("Old Driveway Demo &amp; Haul", "$2.50&ndash;$5/sq ft", "Concrete or asphalt tear-out"),
            ("Paver Sealing", "$1&ndash;$2.50/sq ft", "Penetrating or wet-look film"),
            ("Soldier-Course / Contrast Border", "$12&ndash;$22/linear ft", "Per banded edge"),
        ],
        "faqs": [
            ("Pavers or poured concrete for my driveway?", "Both work in Florida, and we install both, so we&rsquo;ll give you the honest trade-off. Poured concrete costs less up front and goes in faster, but it cracks &mdash; our soil moves, and a monolithic slab has nowhere to put that movement except a crack you can&rsquo;t un-see. Pavers cost more, but the interlocking field flexes with the ground instead of fighting it, and when a section settles or a utility has to come up, we lift those pavers, fix the base, and re-set the same units with no patch line. Pavers also give you color and pattern a slab never will. If budget is the only driver, concrete wins; if you want it to still look right in fifteen years, pavers usually earn the premium."),
            ("How deep does the base really need to be?", "For a driveway carrying vehicle loads over Florida&rsquo;s sandy subgrade, we build a compacted crushed-limerock base typically 8 to 12 inches deep after compaction &mdash; meaningfully deeper than the 4-to-6-inch section a walkway or patio gets. The depth isn&rsquo;t arbitrary: it spreads the weight of a loaded truck across enough structure that the soil underneath never gets overstressed, which is what prevents ruts and dips. We compact in lifts rather than dumping it all at once, because only compacted-in-layers base actually carries load. On soft or especially sandy spots we add a geotextile fabric between soil and base so the two never migrate into each other. Skipping base depth is the number-one reason we get called to redo someone else&rsquo;s paver driveway."),
            ("What keeps weeds and ants out of the joints?", "Polymeric sand. Ordinary joint sand stays loose, and loose sand is exactly what weed seeds root into and what ground-nesting ants tunnel out by the cupful &mdash; both classic Florida paver headaches. Polymeric sand carries a binder that, once swept into the joints and activated with a fine mist, sets up firm and locks the joints together. It resists weed germination, shrugs off ants, and keeps the field interlocked so individual pavers don&rsquo;t wander. It isn&rsquo;t permanent forever &mdash; sun and pressure-washing wear it, and joints want a top-up every several years &mdash; but it&rsquo;s a quick, inexpensive refresh, not a rebuild. We set polymeric sand on every paver driveway we install as part of our standard."),
            ("My pavers settled in one spot &mdash; can it be fixed?", "Yes, and this is the quiet advantage of pavers over a poured slab. If a section settles &mdash; usually because base wasn&rsquo;t compacted right, or a downspout has been washing soil out from under it &mdash; we lift those pavers off, correct and re-compact the base beneath, re-screed the bedding sand, and re-set the very same pavers. No patch, no mismatched concrete, no seam. We&rsquo;ll also trace why it settled so it doesn&rsquo;t simply sink again, which often means redirecting water that was undermining the spot. A localized re-level is a modest repair, not a tear-out, and it&rsquo;s a big part of why a paver driveway can be maintained for decades. We&rsquo;re fully insured and estimates are free."),
        ],
    },
    "paver-patios-walkways": {
        "name": "Paver Patios &amp; Walkways",
        "slug": "paver-patios-walkways",
        "short": "Paver Patios",
        "h1_phrase": "Paver Patios &amp; Walkways",
        "card_image": "card-paver-patios-walkways.webp",
        "icon": "08",
        "intro_lead": "Paver patios, walkways, pool decks, fire pits, and steps &mdash; from tight running-bond paths to wide gravel-joint patios, set on a compacted base and built to stay flat and cool underfoot.",
        "intro_long_p1": "A patio or walkway gets walked, lounged, and entertained on barefoot, so the things that matter here are different from a driveway: comfort, drainage, and a surface that stays put. Under the <strong>Gulf Coast sun</strong>, paver color and texture decide how the deck feels &mdash; lighter tumbled tones near a pool run far cooler underfoot than a dark slab, and we&rsquo;ll steer you toward units that don&rsquo;t bake. Florida&rsquo;s <strong>sandy soil</strong> still needs a real <strong>compacted base</strong>; a patio set straight on raw sand telegraphs every settled spot and rocks under a chair leg within a season. We grade every surface to <strong>shed water away from the house and screen cage</strong>, because standing water is what feeds mildew, undermines pavers, and ruins a lanai. We lock joints against <strong>weeds and ants</strong>, and in <strong>HOA / ARC-governed</strong> Lakewood Ranch villages we match the approved hardscape palette so your project clears review. Every install follows our <strong>Lakewood Ranch Concrete 42-Point Install Standard</strong>, and we offer <strong>free estimates and financing</strong> so the patio you actually want isn&rsquo;t the one you talk yourself out of.",
        "intro_long_p2": "This service covers the full outdoor-living kit &mdash; patios, walkways, pool decks, <strong>spaced gravel-joint paver patios</strong>, <strong>paver fire pits</strong>, and <strong>paver steps</strong>. We set <strong>brick</strong>, <strong>concrete</strong>, and <strong>permeable</strong> pavers; large-format and plank units read modern, tumbled units read old-world, and a gravel or grass joint between widely-spaced pavers gives a soft, garden look that also drains hard. Foot-traffic areas are lighter than a driveway &mdash; typically <strong>30&ndash;50 mm</strong> pavers over a compacted base around <strong>4&ndash;6&Prime;</strong> deep &mdash; but the discipline is identical: screeded bedding sand, true lines, and an <strong>edge restraint</strong> locked along every open edge so the field never creeps. <strong>Fire pits and steps</strong> are built with wall-block and capstones rated for the job and seated on a stable footing. We finish joints with polymeric sand (or gravel where the design calls for it) and talk through <strong>sealing</strong> honestly &mdash; it deepens color and fights stains, but it&rsquo;s an upkeep choice, not a requirement.",
        "scope_items": [
            "Paver patios (brick, concrete &amp; permeable)",
            "Paver walkways &amp; garden paths",
            "Paver pool decks &amp; lanai surfaces",
            "Spaced gravel-joint &amp; grass-joint patios",
            "Paver fire pits with rated wall-block &amp; cap",
            "Paver steps &amp; stair landings",
            "Large-format &amp; plank paver layouts",
            "Compacted crushed-limerock base in lifts",
            "Screeded bedding-sand setting bed",
            "Drainage pitch away from house &amp; screen cage",
            "Concrete &amp; spiked edge restraints",
            "Polymeric-sand &amp; gravel joint finishing",
            "Soldier-course &amp; contrasting borders",
            "Paver sealing (penetrating &amp; wet-look options)",
            "Old slab or paver removal &amp; haul-away",
        ],
        "pricing_rows": [
            ("Concrete Paver Patio / Walkway", "$14&ndash;$20/sq ft installed", "Most-installed foot-traffic tier"),
            ("Brick (Clay) Paver Patio", "$17&ndash;$24/sq ft installed", "Color-fast, classic look"),
            ("Premium / Large-Format Paver", "$19&ndash;$27/sq ft installed", "Plank &amp; oversized units"),
            ("Spaced Gravel-Joint Paver Patio", "$18&ndash;$26/sq ft installed", "Open joints, soft garden look"),
            ("Permeable Paver Patio / Deck", "$20&ndash;$28/sq ft installed", "Drains through the surface"),
            ("Paver Fire Pit (built-in)", "$1,400&ndash;$3,800 each", "Rated wall-block &amp; capstone"),
            ("Paver Steps (per riser)", "$300&ndash;$650 each", "Seated on stable footing"),
            ("Paver Sealing", "$1&ndash;$2.50/sq ft", "Penetrating or wet-look film"),
        ],
        "faqs": [
            ("Will a paver pool deck stay cool enough to walk on?", "Cooler than a dark slab, and the choice of paver is what decides it. Under full Gulf Coast sun, color and texture drive surface temperature far more than material does &mdash; a light, tumbled concrete or clay paver near a pool stays noticeably more comfortable underfoot than a dark, dense unit that soaks up heat all afternoon. Pavers also have an edge over poured concrete here because the jointed field doesn&rsquo;t hold and radiate heat in one unbroken sheet. We steer pool-deck clients toward lighter tones and textured finishes for exactly this reason, and we can show you samples in your own light. If barefoot comfort is the priority, tell us up front &mdash; it genuinely changes which paver we recommend."),
            ("What&rsquo;s a gravel-joint or spaced paver patio?", "It&rsquo;s a patio where the pavers are set with a deliberate gap between them &mdash; an inch or more &mdash; and that gap is filled with fine gravel or planted with a low ground cover instead of tight sand. The look is softer and more organic, a great fit for garden patios and modern large-format layouts. The practical bonus in Florida is drainage: those open joints let rain pass straight down instead of sheeting across the surface, which is why we like them on lots that pond. They do trade a little: gravel joints need occasional topping up and aren&rsquo;t ideal under narrow heels or chair casters. We&rsquo;ll tell you honestly whether the spaced look suits how you&rsquo;ll actually use the space."),
            ("Can you build a fire pit and steps into the patio?", "Yes &mdash; built-in paver fire pits and paver steps are part of this service and a natural extension of a patio project. We build fire pits from wall-block and capstones rated for heat, seated on a stable, compacted footing so the ring stays true and level for years, and we&rsquo;ll set it up for wood or pipe it for gas depending on what you want. Steps and stair landings are built on their own solid footing with the same paver field as the patio so everything reads as one surface. What we don&rsquo;t do is structural or tall retaining work &mdash; we keep to hardscape walls under four feet. If your layout needs grade changes, we&rsquo;ll lay out exactly what fits within that."),
            ("How long do paver patios last, and what upkeep is there?", "A properly based paver patio is a multi-decade surface &mdash; the pavers themselves outlast almost everything else in the yard, and the field is fully repairable, so a settled or stained paver gets lifted and reset rather than patched. The upkeep is light and predictable: an occasional rinse or gentle pressure-wash, a top-up of polymeric joint sand every several years as sun and washing wear it, and a gravel-joint refresh if you went that route. Sealing is optional &mdash; it deepens color and helps shed stains on a patio that hosts a lot of food and drink, but it&rsquo;s an upkeep cycle you opt into, not a requirement. We&rsquo;re fully insured, estimates are free, and we&rsquo;ll lay out the realistic maintenance before you commit."),
        ],
    },
}
