# Service data (part 1) for Lakewood Ranch Concrete — Bradenton / Lakewood Ranch / Sarasota / Tampa Bay.
SERVICES = {
    "concrete-driveways": {
        "name": "Concrete Driveways",
        "slug": "concrete-driveways",
        "short": "Concrete Driveways",
        "h1_phrase": "Concrete Driveways",
        "card_image": "card-concrete-driveways.webp",
        "icon": "01",
        "intro_lead": "Poured-in-place driveways engineered for Gulf Coast heat and shifting soil &mdash; properly jointed, fiber-reinforced, and finished to carry Florida vehicles without the spider-cracking you see two doors down.",
        "intro_long_p1": "A driveway is the largest single slab most homeowners ever pour, and in our Bradenton-to-Sarasota market it is also the one that fails most predictably. The culprit is rarely the concrete itself &mdash; it is what happens underneath and at the edges. Our sandy, expansive subgrade swells and shrinks with the wet season, and a slab placed on un-compacted fill or starved of control joints will telegraph that movement straight up as cracks by its second summer. We have walked Lakewood Ranch driveways that cracked in a grid because nobody cut a relief joint, and others that heaved because the base was never proofrolled. Every driveway we pour runs through our <strong>Lakewood Ranch Concrete 42-Point Install Standard</strong>, which gates the subgrade compaction, slab thickness, and joint layout before any truck is called. When budget is the reason a homeowner wants to thin the slab or skip the base work, we would rather walk through <strong>financing</strong> than cut the step that keeps it flat. Estimates are always free.",
        "intro_long_p2": "We build driveways on two honest choices. A <strong>standard broom-finish slab</strong> &mdash; four inches of fiber-reinforced concrete over a compacted base, saw-cut into proper panels &mdash; is the workhorse that handles the daily car-and-truck load of most Parrish, Ellenton, and Lakewood Ranch homes. When a homeowner wants the driveway to read as a design feature, we step up to <strong>decorative options</strong>: stamped patterns that mimic brick or stone, integral or broadcast color, and exposed-aggregate finishes that hide tire marks and add grip. We spec a true 3,000&ndash;4,000 PSI mix with synthetic fiber, place control joints at roughly ten-foot spacing, and pour against expansion joints where the slab meets the garage and the public sidewalk. For HOA and ARC-governed neighborhoods like Lakewood Ranch, we match the approved color and finish on your submittal so the install clears review the first time. We do not pour structural foundations, load-bearing slabs, or retaining walls &mdash; driveways, flatwork, and the finishes that go with them are what we do.",
        "scope_items": [
            "New driveway pour (4″ fiber-reinforced, broom finish)",
            "Driveway tear-out, haul-away &amp; full replacement",
            "Subgrade excavation, fill &amp; mechanical compaction",
            "Proofrolled, graded base preparation",
            "Thickened-edge pours at driveway aprons",
            "Saw-cut control joints at engineered spacing",
            "Expansion-joint isolation at garage &amp; sidewalk",
            "Stamped &amp; textured decorative finishes",
            "Integral &amp; broadcast color application",
            "Exposed-aggregate finish",
            "Driveway widening &amp; ribbon-strip additions",
            "Apron &amp; right-of-way tie-ins to county standard",
            "Penetrating sealer for stain &amp; UV protection",
            "HOA / ARC color &amp; finish matching for submittals",
            "Site cleanup, wash-out containment &amp; debris removal",
        ],
        "pricing_rows": [
            ("4″ Standard Concrete Driveway", "$8&ndash;$12/sq ft installed", "Broom finish, fiber-reinforced"),
            ("Tear-Out &amp; Replace (existing driveway)", "$11&ndash;$16/sq ft installed", "Demo &amp; haul of old slab included"),
            ("Stamped Decorative Driveway", "$15&ndash;$24/sq ft installed", "Brick, stone &amp; slate patterns"),
            ("Exposed-Aggregate Driveway", "$13&ndash;$19/sq ft installed", "Hides tire marks, adds grip"),
            ("Integral / Broadcast Color", "+$1.50&ndash;$3.50/sq ft", "Added to any finish"),
            ("Driveway Widening (per added strip)", "$9&ndash;$14/sq ft installed", "Tied to existing slab"),
            ("Extra Base Prep / Poor Subgrade", "$2&ndash;$5/sq ft", "Where fill or compaction is required"),
            ("Penetrating Sealer", "$0.85&ndash;$1.75/sq ft", "UV &amp; stain protection, reapply ~3 yrs"),
        ],
        "faqs": [
            ("Why do so many Florida driveways crack, and can you prevent it?", "Concrete cracks &mdash; the honest goal is to control where, not to promise it never happens. Most failures we are called to fix come from one of three skipped steps: an un-compacted sandy base that settles, missing or mis-spaced control joints, or a slab poured too thin for the load. We address all three before the truck arrives. The subgrade gets graded and mechanically compacted, the slab carries synthetic fiber, and we saw-cut control joints at roughly ten-foot spacing so the inevitable shrinkage relieves itself in a straight, intended line instead of a random web across your apron. Hairline joint cracking is normal and harmless; a heaving, grid-cracked driveway is a prep failure, and that is exactly what our process is built to prevent."),
            ("How thick should my driveway be, and how long before I can drive on it?", "Four inches of fiber-reinforced concrete over a compacted base handles standard cars and light trucks, which covers the vast majority of homes from Parrish to Sarasota. If you park an RV, a boat trailer, or a heavy work truck, we step the slab up to five or six inches and adjust the base accordingly &mdash; we will ask about your heaviest vehicle during the free estimate. On timing: you can walk it the next day, but keep vehicles off for seven full days. The slab keeps gaining strength for weeks, so we ask you to avoid parking the heaviest loads right at the edges for the first month while it fully cures."),
            ("Can you match my HOA or ARC requirements in Lakewood Ranch?", "Yes, and we plan for it from the first visit. Many Lakewood Ranch and Country Club neighborhoods govern driveway color, finish, and even joint pattern through architectural review, and a beautiful pour that does not match the submittal can get flagged after the fact. We pull the approved palette, mock up the color and finish you intend to use, and document it so the install clears ARC review cleanly. If your community requires a specific paver-look or banded border, we match it in stamped or colored concrete. We do not handle the structural or drainage engineering some submittals require &mdash; flatwork, finish, and color matching are our lane."),
            ("Should I repair my old driveway or tear it out and replace it?", "It depends on what is actually failing. Surface scaling, a few isolated cracks, or a stained-but-sound slab can often be cleaned, repaired, and sealed for far less than replacement. But once a driveway has heaved at the joints, cracked in a grid, or settled into puddling low spots, the damage is in the base, not the surface &mdash; and patching a base problem just buys you a year. During the free estimate we read the crack pattern and check for movement at the joints to tell you honestly which camp you are in. When replacement is the right call, our tear-out price already includes demo and haul of the old slab so there are no surprises."),
        ],
    },
    "concrete-patios": {
        "name": "Concrete Patios",
        "slug": "concrete-patios",
        "short": "Concrete Patios",
        "h1_phrase": "Concrete Patios",
        "card_image": "card-concrete-patios.webp",
        "icon": "02",
        "intro_lead": "Outdoor living slabs &mdash; broom-finish, stamped, or stained &mdash; built to drain away from the house, beat the Gulf Coast sun, and turn a bare backyard into the room you actually use ten months a year.",
        "intro_long_p1": "A patio is where Florida living actually happens, and it is also where two details quietly decide whether you love it or fight it for years: drainage and surface temperature. We pour every patio with a deliberate slope &mdash; a fall away from the house and any pool cage &mdash; because a flat slab in our summer downpours becomes a standing-water complaint by the first storm season, and water pooling against your slab edge is how the sandy subgrade starts to undermine it. The second detail is heat: a dark, dense surface in full Lakewood Ranch sun gets brutal underfoot, so we steer homeowners toward lighter colors and textured finishes that stay walkable. Every patio runs through our <strong>Lakewood Ranch Concrete 42-Point Install Standard</strong>, which gates the grade, slope, and joint plan before the pour. <strong>Free estimates</strong> and <strong>financing</strong> are available, because we would rather you build the patio you want once than redo a too-small slab in three years.",
        "intro_long_p2": "We build patios across a real range of finishes, and we match the finish to how you will live on it. A <strong>broom-finish slab</strong> is the practical, grippy, budget-friendly base for a screened lanai or a simple grill-and-table zone. <strong>Stamped concrete</strong> presses brick, slate, wood-plank, or flagstone texture into the wet slab and, with integral color and a release, reads convincingly as far pricier hardscape at a fraction of paver labor. <strong>Stained and polished overlays</strong> give an existing sound slab a brand-new acid-stained or mottled finish without a full tear-out. We spec a 3,000&ndash;4,000 PSI fiber-reinforced mix, cut control joints into a pattern that complements the layout instead of fighting it, and seal decorative work with a UV-stable product so the color holds against that relentless sun. We pour patios, extensions, walkways, and fire-pit pads &mdash; not foundations, structural slabs, or retaining walls over four feet.",
        "scope_items": [
            "New patio slab pour (broom finish, fiber-reinforced)",
            "Patio extensions &amp; additions to existing slabs",
            "Stamped concrete patios (brick, slate, wood-plank, flagstone)",
            "Acid-stained &amp; integrally colored finishes",
            "Decorative overlay resurfacing of sound slabs",
            "Engineered slope &amp; drainage away from the home",
            "Screened-lanai &amp; pool-cage slab prep",
            "Saw-cut control joints in a layout-matched pattern",
            "Expansion-joint isolation at house &amp; footers",
            "Walkway &amp; path connections to the patio",
            "Fire-pit &amp; grill-station pads",
            "Step &amp; landing forming where grade requires",
            "Border &amp; banding accent details",
            "UV-stable sealer for color &amp; stain retention",
            "Site cleanup, wash-out containment &amp; debris removal",
        ],
        "pricing_rows": [
            ("Broom-Finish Patio Slab", "$7&ndash;$11/sq ft installed", "4″ fiber-reinforced, sloped to drain"),
            ("Stamped Concrete Patio", "$14&ndash;$22/sq ft installed", "Pattern, color &amp; release included"),
            ("Acid-Stained Finish", "+$3&ndash;$7/sq ft", "Mottled, variegated color"),
            ("Decorative Overlay (sound slab)", "$8&ndash;$15/sq ft", "Resurface without tear-out"),
            ("Patio Extension (tied to existing)", "$8&ndash;$13/sq ft installed", "Doweled into current slab"),
            ("Connecting Walkway", "$9&ndash;$14/sq ft installed", "Path to patio, pool, or drive"),
            ("Fire-Pit / Grill Pad", "$650&ndash;$1,600", "Sized to your equipment"),
            ("UV-Stable Decorative Sealer", "$1&ndash;$2/sq ft", "Protects stamp &amp; stain color"),
        ],
        "faqs": [
            ("Does a concrete patio get too hot to walk on in Florida?", "It can, and that is mostly a choice made at the color and finish stage rather than something you are stuck with. Dark, dense, smooth surfaces in full Lakewood Ranch sun absorb and hold heat &mdash; the same reason a dark car seat is punishing in July. We steer homeowners toward lighter integral colors and textured or broom finishes, which reflect more sun and stay noticeably cooler underfoot than a dark, slick slab. If you want a deeper stamped color for looks, pairing it with shade from your cage, pergola, or roofline keeps it comfortable. We will talk through where the afternoon sun lands on your specific yard during the free estimate so the finish fits how you will actually use the space."),
            ("Stamped concrete or pavers &mdash; which makes more sense?", "Both look great; they fail and age differently, and we will give you the honest trade-off. Stamped concrete is one continuous slab, so there are no joints for weeds or ants to colonize and nothing to sink unevenly &mdash; but if it ever cracks, the repair is harder to hide than swapping a paver. Pavers flex with ground movement and let you lift and reset a section, but the sand joints need periodic attention and can host weeds in our climate. For a clean, low-maintenance, design-forward patio at a friendlier labor cost, stamped concrete usually wins; if you specifically want a lift-and-reset surface, pavers earn their keep. We install the concrete side and will tell you plainly when pavers are the better fit."),
            ("Can you resurface my old, stained patio instead of tearing it out?", "Often, yes &mdash; if the underlying slab is structurally sound. A decorative overlay or acid stain can give a dated, discolored, but solid patio a completely new finish for far less than a full replacement and with far less mess. The deciding factor is what is wrong underneath: surface staining, light scaling, and dullness are perfect overlay candidates, but if the slab has heaved, cracked through, or settled into puddles, an overlay just hides a problem that will resurface. We check the slab for movement and drainage during the free estimate and tell you honestly whether you are looking at a resurface or a replacement &mdash; we will not sell you an overlay on a slab that needs to come out."),
            ("How big should my patio be, and how long does it take to build?", "Size it to the furniture and the use, not the leftover yard. A grill-and-bistro corner works at around ten by ten, a full dining-plus-lounge outdoor room usually wants sixteen by twenty or more, and we will mock the footprint out with your actual furniture in mind so you are not boxed in later. On timeline: a typical patio is a multi-day job &mdash; layout and forming, then the pour, then joint cutting, and for stamped or stained work an added day or two for coloring and sealing. You can walk a broom-finish slab the next day but should keep furniture and heavy use off for about a week while it cures. The real schedule lives in your written estimate."),
        ],
    },
    "concrete-pool-decks": {
        "name": "Concrete Pool Decks",
        "slug": "concrete-pool-decks",
        "short": "Concrete Pool Decks",
        "h1_phrase": "Concrete Pool Decks",
        "card_image": "card-concrete-pool-decks.webp",
        "icon": "03",
        "intro_lead": "Slip-resistant, cool-to-the-touch pool decks &mdash; textured stamped, cool-deck, and paver-look finishes built to shed water, beat barefoot heat, and stand up to chlorine and salt around Lakewood Ranch pools.",
        "intro_long_p1": "A pool deck is the most demanding flatwork we pour, because it has to satisfy three things at once that pull against each other: it must be <strong>slip-resistant</strong> when wet, <strong>cool enough</strong> for bare feet in full sun, and tough enough to shrug off constant chlorine, salt, and standing splash-out. Get the texture too smooth and it is a liability around an active pool; get the color too dark and nobody can cross it at two in the afternoon. We design every deck to drain decisively away from the coping and the screen-cage track, because water that ponds against a Lakewood Ranch cage footer is how rust stains and undermining start. Every pool deck runs through our <strong>Lakewood Ranch Concrete 42-Point Install Standard</strong>, which gates the slope, texture, and joint plan around the pool shell before the pour. We are <strong>fully insured</strong>, estimates are <strong>free</strong>, and <strong>financing</strong> is available so you can build the deck the pool deserves.",
        "intro_long_p2": "We finish pool decks three honest ways and pick to your priorities. A <strong>textured stamped deck</strong> presses a non-slip stone, slate, or shell pattern into the slab with integral color, giving a high-end look that grips when wet. A <strong>cool-deck-style acrylic finish</strong> is a sprayed, knock-down texture engineered specifically to reflect heat and stay walkable barefoot &mdash; the classic Florida answer to the midday-sun problem &mdash; and it renews an existing sound deck without a tear-out. A <strong>paver-look stamped border</strong> with a broom-finish field blends grip, looks, and budget. Whatever the finish, we specify a fiber-reinforced mix, isolate the deck from the pool shell and cage with proper joints so the two move independently, and seal decorative work with a UV-stable, slip-rated sealer that holds up to pool chemistry. We pour and resurface pool decks, surrounds, and connecting walkways &mdash; we do not handle the pool shell, structural slabs, foundations, or retaining walls.",
        "scope_items": [
            "New pool-deck pour (fiber-reinforced, slip-rated finish)",
            "Cool-deck-style acrylic knock-down resurfacing",
            "Textured stamped finishes (stone, slate, shell &amp; non-slip)",
            "Paver-look stamped borders with broom-finish field",
            "Integral &amp; broadcast color for heat reduction",
            "Engineered slope &amp; drainage away from coping &amp; cage",
            "Isolation joints between deck, pool shell &amp; cage track",
            "Coping tie-in &amp; transition detailing",
            "Deck-around-spa &amp; sun-shelf surrounds",
            "Resurfacing of sound but dated existing decks",
            "Connecting walkways to lanai &amp; home",
            "Crack repair &amp; spall patching before resurfacing",
            "Saw-cut control joints in a layout-matched pattern",
            "UV-stable, slip-rated, chlorine-resistant sealer",
            "Site cleanup, wash-out containment &amp; debris removal",
        ],
        "pricing_rows": [
            ("Broom-Finish Pool Deck", "$8&ndash;$12/sq ft installed", "Sloped, slip-textured, fiber-reinforced"),
            ("Cool-Deck Acrylic Resurface", "$5&ndash;$9/sq ft", "Heat-reflective, over sound slab"),
            ("Textured Stamped Pool Deck", "$15&ndash;$24/sq ft installed", "Non-slip stone, slate &amp; shell"),
            ("Paver-Look Border + Field", "$12&ndash;$18/sq ft installed", "Stamped border, broom field"),
            ("Integral / Broadcast Color", "+$1.50&ndash;$3.50/sq ft", "Lighter tones run cooler"),
            ("Crack &amp; Spall Repair (pre-resurface)", "$8&ndash;$20/linear ft", "Prep so the new finish lasts"),
            ("Connecting Walkway", "$9&ndash;$14/sq ft installed", "Deck to lanai or home"),
            ("Slip-Rated UV / Chlorine Sealer", "$1.25&ndash;$2.50/sq ft", "Reapply roughly every 2&ndash;3 yrs"),
        ],
        "faqs": [
            ("How do you keep a pool deck from getting slippery or scorching hot?", "Those are the two non-negotiables of a pool deck, and we solve them at the finish stage. For slip resistance, we use textured stamped patterns, broom finishes, or a knock-down acrylic &mdash; never a smooth, troweled surface around water, which is a genuine hazard when wet. For heat, the levers are color and finish: lighter integral tones reflect more sun, and cool-deck-style acrylic coatings are specifically engineered to stay walkable barefoot in midday Florida sun. The two goals work together, since the same textured, lighter finishes that grip also tend to run cooler. During the free estimate we look at where the afternoon sun hits your deck and pick the combination that keeps it both safe and barefoot-friendly."),
            ("Can you resurface my cracked, dated pool deck instead of replacing it?", "Usually yes, and it is the most common pool-deck job we do. If the slab underneath is structurally sound, a cool-deck acrylic finish or a stamped overlay can give a stained, dated, or chalky deck a brand-new slip-rated surface for far less than a tear-out. The honest prerequisite is prep: we repair cracks and patch spalled, flaking areas first, because a resurface laid over unaddressed damage just telegraphs the same cracks back through. If the deck has heaved, settled into puddles, or cracked clear through from a base failure, an overlay is the wrong fix and we will tell you so. We read the slab during the free estimate and give you a straight answer."),
            ("Will chlorine, salt, and pool chemicals wreck the concrete?", "Not when the deck is built and sealed for it &mdash; that is exactly what separates a pool-deck pour from ordinary flatwork. Constant chlorine, salt-system runoff, and splash-out will etch, discolor, and surface-spall unprotected concrete over time, so we finish decorative decks with a UV-stable, slip-rated sealer chosen to resist pool chemistry, and we slope the deck so chemical-laden water drains off instead of sitting in low spots. The sealer is maintenance, not a one-time step: plan to reapply roughly every two to three years in our climate to keep both the protection and the color fresh. We hand you the care details at the walkthrough so you know exactly what the deck needs."),
            ("Why does the deck need to be separated from the pool and the cage?", "Because they all move, and they do not move together. The pool shell, the screen-cage footers, and the deck slab each respond differently to our wet-and-dry soil cycles, and if you pour the deck tight against them with no relief, that differential movement cracks the deck right at the coping or the cage track &mdash; the worst place for it. We install isolation joints between the deck and the pool shell and around the cage so each element can shift independently without dragging the others. It is an invisible detail that does nothing for the photos and everything for whether your deck still looks new in five years. Skipping it is one of the most common reasons we get called to redo someone else's pool deck."),
        ],
    },
}
