# Lakewood Ranch Concrete — service data (part 2 of N)
SERVICES = {
    "stamped-concrete": {
        "name": "Stamped &amp; Decorative Concrete",
        "slug": "stamped-concrete",
        "short": "Stamped Concrete",
        "h1_phrase": "Stamped &amp; Decorative Concrete",
        "card_image": "card-stamped-concrete.webp",
        "icon": "04",
        "intro_lead": "Stamped patios, pool decks, driveways, and walkways that read as travertine, slate, brick, or wood plank &mdash; poured, textured, and sealed to hold their color under the Gulf Coast sun.",
        "intro_long_p1": "Stamped concrete is the upgrade most Lakewood Ranch and Bradenton homeowners reach for when a plain gray slab no longer matches a house they&rsquo;ve put real money into, and it&rsquo;s the one decorative product where Florida&rsquo;s climate punishes a shortcut the fastest. Our <strong>Gulf Coast sun is brutal on color</strong> &mdash; an integral color and release that wasn&rsquo;t UV-stable will chalk and fade two shades inside three summers, which is why the product we choose and the sealer we top it with matter more here than almost anywhere. The <strong>sandy, expansive soil</strong> under most of our 34211 and 34202 jobs moves with the wet season, so a stamped slab that skips proper sub-base compaction and control joints will crack straight through a $14-a-foot finish. Every stamped pour we place runs through our <strong>Lakewood Ranch Concrete 42-Point Install Standard</strong>, which is exactly where compaction, joint layout, and cure are logged. We also work to your community&rsquo;s <strong>HOA / ARC color and pattern rules</strong> up front, and <strong>Free Estimates</strong> and <strong>financing</strong> are on the table before you commit.",
        "intro_long_p2": "We build stamped work two honest ways and tell you which your project actually needs. A <strong>monolithic stamped pour</strong> &mdash; integrally colored concrete, texture mats pressed into the wet surface, an antiquing release for depth &mdash; is our call for new patios, driveways, and walkways where we control the whole slab. A <strong>stamped overlay</strong> bonds a polymer-modified topping over a sound existing slab, the right answer when the concrete underneath is structurally fine but tired, and it spares you a full tear-out. Our texture library covers <strong>Ashlar slate, Roman travertine, seamless stone, running-bond brick, and weathered wood plank</strong>, in earth tones that suit a Mediterranean or coastal-transitional Florida home. We finish every stamped surface with a breathable, UV-stable acrylic sealer and we&rsquo;re blunt about upkeep: a stamped deck wants a re-seal every two to three years here, and we&rsquo;d rather tell you that now than have you think it&rsquo;s a one-and-done floor.",
        "scope_items": [
            "Monolithic stamped patios (integral color + texture mats)",
            "Stamped pool decks &amp; lanai surfaces",
            "Stamped driveways &amp; entry aprons",
            "Stamped walkways &amp; garden paths",
            "Stamped overlays over sound existing slabs",
            "Ashlar slate &amp; Roman travertine patterns",
            "Seamless stone &amp; running-bond brick textures",
            "Weathered wood-plank stamp work",
            "Integral &amp; broadcast color hardeners",
            "Antiquing release for two-tone depth",
            "Decorative saw-cut &amp; control-joint layout",
            "Border &amp; banding accents in contrasting color",
            "UV-stable acrylic sealer application",
            "HOA / ARC color &amp; pattern matching",
            "Re-seal &amp; color-refresh on existing stamped work",
        ],
        "pricing_rows": [
            ("Stamped Patio (single pattern, single color)", "$13–$18/sq ft installed", "New monolithic pour, sealed"),
            ("Stamped Patio (multi-pattern / two-tone)", "$17–$24/sq ft installed", "Border &amp; banding accents"),
            ("Stamped Pool Deck", "$15–$22/sq ft installed", "Slip-texture &amp; cool-tone sealer"),
            ("Stamped Driveway", "$14–$20/sq ft installed", "Thicker section &amp; rebar for vehicle loads"),
            ("Stamped Overlay (over sound slab)", "$9–$15/sq ft installed", "No full tear-out required"),
            ("Decorative Walkway (stamped, 4″ thick)", "$13–$19/sq ft installed", "Path &amp; garden runs"),
            ("Re-Seal &amp; Color Refresh", "$2.25–$4.25/sq ft", "Every 2–3 yrs in Gulf Coast sun"),
            ("Old Slab Removal &amp; Haul", "$3.50–$7/sq ft", "Demo &amp; disposal of existing concrete"),
        ],
        "faqs": [
            ("Will stamped concrete fade in the Florida sun?", "Any colored concrete will shift a little over years of direct Gulf Coast sun &mdash; that&rsquo;s physics, not a defect &mdash; but how much depends almost entirely on the color system and the sealer. We use UV-stable integral colors rather than cheap surface dyes, and we top every stamped surface with a UV-resistant acrylic that takes the brunt of the exposure instead of the concrete itself. The honest trade-off is maintenance: that sealer wears, and a stamped deck in full Bradenton sun wants a re-seal roughly every two to three years to keep the color rich and the surface protected. Skip the re-seals and yes, it&rsquo;ll chalk and dull. Keep up with them and a stamped patio holds its look for a very long time."),
            ("Is stamped concrete slippery around a pool?", "It can be if it&rsquo;s sealed wrong, and that&rsquo;s the single most common complaint we&rsquo;re called to fix on someone else&rsquo;s pool deck. The fix is built into how we finish it: for any pool deck or wet area we broadcast a fine micro-grit additive into the sealer, which restores grip without making the surface feel rough underfoot. We also steer pool-deck clients toward lighter, cooler color tones, because a dark stamped deck in Florida soaks up heat and gets uncomfortable barefoot by midday. Tell us it&rsquo;s a pool surround at the estimate and we spec the texture and the sealer for bare feet from the start &mdash; it&rsquo;s not an upgrade, it&rsquo;s just how a wet-area deck should be done."),
            ("New stamped pour or a stamped overlay &mdash; which do I need?", "It comes down to what&rsquo;s under your feet right now. If you&rsquo;re starting from dirt, or your existing slab is cracked, heaved, or sinking, you want a new monolithic pour &mdash; we control the sub-base, the steel, and the joints, and the color goes all the way through. If your current slab is structurally sound and flat but just plain or dated, a stamped overlay bonds a decorative topping right over it for noticeably less money and far less demolition. The catch is honesty about the base: an overlay only lasts if the slab beneath it is solid, so we check it before we ever quote one. We won&rsquo;t lay a pretty overlay over a slab that&rsquo;s going to keep cracking under it."),
            ("Will stamped concrete crack?", "All concrete cracks eventually &mdash; the question is whether it cracks where we plan it to or randomly across your new finish. On our sandy, seasonally shifting soil, the defense is the prep nobody sees: a properly compacted sub-base, the right slab thickness and steel for the load, and control joints cut on a deliberate grid so the slab relieves stress along clean lines instead of tearing through your travertine pattern. That whole sequence is part of our 42-Point Install Standard and it&rsquo;s logged on your job. We won&rsquo;t promise a slab that never moves &mdash; nobody honest can &mdash; but we can build it so the inevitable movement lands in a saw-cut joint where you&rsquo;ll never notice it, not across the middle of your patio."),
        ],
    },
    "concrete-slabs": {
        "name": "Concrete Slabs &amp; Pads",
        "slug": "concrete-slabs",
        "short": "Concrete Slabs",
        "h1_phrase": "Concrete Slabs &amp; Pads",
        "card_image": "card-concrete-slabs.webp",
        "icon": "05",
        "intro_lead": "Shed pads, AC and generator pads, RV and boat pads, parking aprons, sidewalks, and walkways &mdash; poured flat, pitched to drain, and built for the load they&rsquo;ll actually carry.",
        "intro_long_p1": "A flatwork pad looks like the simplest concrete there is, and that&rsquo;s exactly why so many of them fail early across Bradenton, Parrish, and Lakewood Ranch. The slab is only as good as the ground we put it on, and our <strong>sandy, expansive Florida soil</strong> is unforgiving: a shed or RV pad poured on un-compacted fill settles unevenly the first wet season, and a slab that doesn&rsquo;t shed water sits in standing rain and starts <strong>spalling</strong> at the surface within a couple of years. <strong>Pitch matters as much as thickness</strong> &mdash; every pad we place is sloped to drain away from structures, because flat-and-pretty is useless if it ponds. We also size the slab and steel to the real load: a 4&Prime; sidewalk and a 6&Prime; RV pad are not the same pour, and we won&rsquo;t pretend they are. Every pad runs through our <strong>Lakewood Ranch Concrete 42-Point Install Standard</strong>, where sub-base compaction, thickness, slope, and joint spacing are checked and logged. <strong>Free Estimates</strong> and <strong>financing</strong> are available, and we&rsquo;ll flag any HOA / ARC setback or permit issue before we pour.",
        "intro_long_p2": "We pour to the job. <strong>Shed, AC, generator, and equipment pads</strong> get a compacted base, a 4&Prime; to 6&Prime; section, and fiber or welded-wire reinforcement so the pad carries point loads without cracking. <strong>RV, boat, and trailer pads</strong> step up to a 6&Prime; section with a #4 rebar grid, because the wheel loads from a loaded coach are in a different league than a garden shed. <strong>Parking pads and driveway aprons</strong> are pitched to the street and tied in clean. <strong>Sidewalks and walkways</strong> get a 4&Prime; section, hand-tooled or broom-finished for grip, with control joints cut on the right spacing so they crack at the lines instead of across the path. We use a <strong>3,000 to 4,000 PSI mix</strong> sized to the application, isolation joints where slabs meet a foundation or column, and a broom finish that holds traction when our afternoon storms hit. What we don&rsquo;t do is structural or load-bearing foundation work &mdash; these are flatwork pads and slabs-on-grade, and we keep our quotes honest about that line.",
        "scope_items": [
            "Shed &amp; storage-building pads",
            "AC condenser &amp; generator pads",
            "Equipment &amp; mini-split pads",
            "RV, boat &amp; trailer pads (6″ + rebar)",
            "Parking pads &amp; driveway aprons",
            "Sidewalks &amp; walkways (4″, broom finish)",
            "Grill, fire-pit &amp; patio pads",
            "Compacted &amp; tested sub-base preparation",
            "Fiber-mesh &amp; welded-wire reinforcement",
            "#4 rebar grids for vehicle loads",
            "Positive drainage pitch away from structures",
            "Control-joint &amp; isolation-joint layout",
            "Broom, trowel &amp; hand-tooled finishes",
            "Vapor barrier under covered / enclosed pads",
            "Old pad removal &amp; haul-away",
        ],
        "pricing_rows": [
            ("Shed / Equipment Pad (4″, fiber)", "$7–$11/sq ft installed", "Compacted base, reinforced"),
            ("AC / Generator Pad (small)", "$275–$650 each", "Sized &amp; pitched to the unit"),
            ("RV / Boat Pad (6″, #4 rebar)", "$9–$14/sq ft installed", "Heavy wheel-load section"),
            ("Parking Pad / Driveway Apron", "$8–$13/sq ft installed", "Pitched &amp; tied to existing"),
            ("Sidewalk / Walkway (4″, broom)", "$8–$13/sq ft installed", "Control joints on grid"),
            ("Patio / Grill Pad (broom finish)", "$7–$12/sq ft installed", "Standard gray, sealed optional"),
            ("Thickened-Edge Upgrade", "+$2.50–$4.50/lin ft", "Added perimeter for point loads"),
            ("Old Pad Removal &amp; Haul", "$3.50–$7/sq ft", "Demo &amp; disposal of existing slab"),
        ],
        "faqs": [
            ("How thick should my concrete pad be?", "It&rsquo;s set entirely by what sits on it. A sidewalk or a garden-shed pad is fine at 4 inches with fiber or wire reinforcement. A pad carrying real weight &mdash; an RV, a loaded boat trailer, a heavy generator &mdash; needs to step up to 6 inches with a #4 rebar grid, because the point loads from those will crack a thin slab even on a perfect base. Driveway aprons that see vehicle traffic land in the same 6-inch range. We size the section to your actual use at the estimate rather than pouring everything the same and hoping &mdash; over-building a sidewalk wastes your money and under-building an RV pad wastes the whole slab. Tell us the heaviest thing that&rsquo;ll ever park on it and we spec from there."),
            ("Why do concrete pads crack and how do you prevent it?", "Two things crack pads in our area: poor sub-base and missing joints. Our sandy, expansive soil settles unevenly when it isn&rsquo;t compacted before the pour, so the slab loses support and cracks to follow the void &mdash; which is why compaction is a logged step in our 42-Point Standard, not an afterthought. The second defense is control joints, cut or tooled on the right grid so the slab relieves its natural shrinkage stress along clean planned lines instead of tearing randomly. We also keep slabs isolated from foundations and columns so the two don&rsquo;t fight each other as they move. We can&rsquo;t promise concrete that never cracks &mdash; that doesn&rsquo;t exist &mdash; but we can build it so any crack lands in a joint where it&rsquo;s invisible and harmless."),
            ("Do I need a permit or HOA approval for a new pad?", "Often, yes, and it depends on size, location, and your community. Many Lakewood Ranch and Bradenton municipalities require a permit once a slab passes a certain square footage or sits near a setback or easement, and most HOAs want ARC approval for anything visible from the street &mdash; an RV pad or a front walkway especially. We&rsquo;re not your permitting office, but we&rsquo;ve poured enough pads in these communities to flag when you&rsquo;re likely to need approval and to keep the work inside setback and drainage rules so it passes. We&rsquo;ll raise it at the free estimate rather than letting you find out after the truck leaves. Getting the paperwork right up front is far cheaper than tearing out a pad that was placed over an easement."),
            ("How long before I can use my new slab?", "You can usually walk on a fresh pad within 24 to 48 hours, but using it for its real purpose takes longer. Concrete reaches roughly 70 percent of its strength in about a week and keeps curing for a full 28 days. For a sidewalk or shed pad, light use after a few days is fine. For an RV, boat, or vehicle pad, we ask you to hold off parking anything heavy for at least seven days, and ideally longer in cooler weather &mdash; rolling a loaded coach onto a slab that hasn&rsquo;t built strength is a reliable way to crack a pad you just paid for. We&rsquo;ll give you the specific timeline for your pour and mix at handoff, not a guess."),
        ],
    },
    "concrete-resurfacing": {
        "name": "Concrete Resurfacing &amp; Repair",
        "slug": "concrete-resurfacing",
        "short": "Resurfacing &amp; Repair",
        "h1_phrase": "Concrete Resurfacing &amp; Repair",
        "card_image": "card-concrete-resurfacing.webp",
        "icon": "06",
        "intro_lead": "Decorative overlays, cool-deck-style pool deck resurfacing, crack and spalling repair, and sealing &mdash; restoring tired Gulf Coast concrete without the cost of a full tear-out.",
        "intro_long_p1": "Resurfacing is the highest-return concrete decision most Bradenton and Lakewood Ranch homeowners don&rsquo;t know they have. A pool deck or driveway that&rsquo;s gone gray, <strong>spalled</strong>, and webbed with hairline cracks looks finished, but the slab underneath is usually sound &mdash; and our <strong>Gulf Coast climate</strong> is exactly what aged the surface, not the structure. Years of UV, salt air near the coast, pool chemicals, and our wet-season freeze-free-but-soaking cycle flake the top layer off a slab while the concrete below stays solid. That&rsquo;s the slab we resurface instead of demolish. The honest first step is telling the difference: a <strong>surface problem</strong> &mdash; spalling, fading, surface crazing &mdash; is a resurfacing candidate, while a slab that&rsquo;s <strong>heaved, sunk, or cracked clean through from soil movement</strong> needs different work, and we&rsquo;ll say so. <strong>Pool decks bake in the Florida sun</strong>, so deck resurfacing is as much about a cooler, grippier walking surface as it is about looks. Every job runs through our <strong>42-Point Install Standard</strong>, and <strong>Free Estimates</strong> plus <strong>financing</strong> are available.",
        "intro_long_p2": "We match the method to the damage. A <strong>polymer-modified overlay</strong> &mdash; a thin, bonded cement topping &mdash; resurfaces a sound but ugly slab and can be left smooth, knock-down textured, or stamped. <strong>Cool-deck-style pool deck resurfacing</strong> lays a textured, light-toned acrylic-cement coating that runs noticeably cooler underfoot and adds slip resistance exactly where bare feet need it. For damage, we do honest repair: we rout and fill <strong>cracks</strong> with flexible or rigid fillers depending on whether the crack still moves, we patch <strong>spalling and surface delamination</strong> back to a sound, level surface, and we <strong>re-seal</strong> with a breathable, UV-stable sealer that keeps Florida moisture out of the slab. We&rsquo;re upfront about the line we don&rsquo;t cross: resurfacing and repair restore the surface of a structurally sound slab. We don&rsquo;t do foundations, structural or load-bearing repair, or retaining walls over four feet &mdash; if a slab has failed structurally, an overlay only hides the problem, and we&rsquo;ll tell you that instead of selling you a coating.",
        "scope_items": [
            "Polymer-modified decorative overlays",
            "Cool-deck-style pool deck resurfacing",
            "Knock-down &amp; textured overlay finishes",
            "Spray-texture &amp; broom-finish coatings",
            "Stamped overlays over sound slabs",
            "Crack routing &amp; flexible-filler repair",
            "Spalling &amp; surface-delamination patching",
            "Surface grinding &amp; profile prep for bonding",
            "Pool deck slip-resistant re-coating",
            "Driveway &amp; walkway resurfacing",
            "Patio &amp; lanai surface restoration",
            "Color refresh &amp; antiquing on faded surfaces",
            "Breathable UV-stable sealing",
            "Joint cleaning &amp; re-caulking",
            "Pressure-wash &amp; surface decontamination prep",
        ],
        "pricing_rows": [
            ("Decorative Overlay (smooth / spray-texture)", "$6–$11/sq ft installed", "Bonded to sound slab"),
            ("Cool-Deck-Style Pool Deck Resurface", "$7–$13/sq ft installed", "Cooler, slip-resistant finish"),
            ("Stamped Overlay (patterned)", "$9–$15/sq ft installed", "Texture &amp; color over sound slab"),
            ("Crack Repair (rout &amp; fill)", "$8–$16/lin ft", "Flexible or rigid by crack type"),
            ("Spalling / Surface Patch", "$9–$18/sq ft", "Back to level, sound surface"),
            ("Clean &amp; Re-Seal (existing concrete)", "$1.75–$3.75/sq ft", "Breathable UV-stable sealer"),
            ("Pressure-Wash &amp; Prep", "$0.40–$0.90/sq ft", "Required before any coating"),
            ("Color Refresh / Antiquing", "$2.25–$4.50/sq ft", "Revive faded decorative work"),
        ],
        "faqs": [
            ("Can my old pool deck be resurfaced or does it need replacing?", "Most of the time it can be resurfaced, and that&rsquo;s a fraction of the cost of tear-out and re-pour. The deciding question is whether the problem is on the surface or in the slab. Spalling, flaking, fading, and the fine spider-web crazing that comes from years of Florida sun and pool chemistry are surface issues &mdash; the slab beneath is sound, and a cool-deck-style overlay bonds right over it for a cooler, grippier, fresh-looking deck. What can&rsquo;t be resurfaced away is a slab that&rsquo;s heaved, sunk, or cracked clean through from soil movement, because an overlay over a moving slab will just crack again. We check the slab before we quote, and if it&rsquo;s structural we tell you &mdash; we won&rsquo;t coat over a problem and call it fixed."),
            ("Will a resurfacing overlay just crack again?", "Only if it&rsquo;s bonded to a slab that&rsquo;s still moving or wasn&rsquo;t prepped right &mdash; and both are avoidable. An overlay is only as good as its bond, so we profile the surface by grinding or etching, clean it to bare sound concrete, and treat any existing crack before we coat. A static hairline crack gets routed and filled rigid so it stays put; a crack that still moves gets a flexible filler and sometimes an isolation detail so the overlay doesn&rsquo;t telegraph it. What we won&rsquo;t do is float a fresh overlay over an actively cracking, structurally failing slab and pretend the problem&rsquo;s gone &mdash; it&rsquo;ll reappear in the new surface within a season. Honest prep on a sound slab is what makes an overlay last; skipping it is why other people&rsquo;s overlays fail."),
            ("What causes concrete spalling in Florida, and can you fix it?", "Spalling &mdash; the surface flaking and popping off in patches &mdash; is one of the most common things we&rsquo;re called for here. In our climate it&rsquo;s usually some mix of trapped moisture, salt and pool chemicals near the surface, an original pour that was over-troweled or had too much water, and years of UV. Water gets into the top layer, and the surface delaminates from the sound concrete below. The fix depends on depth: shallow spalling we grind, patch back to level, and seal; widespread spalling is often best solved with a full bonded overlay that gives you a uniform new surface instead of a patchwork. The key is sealing it afterward with a breathable, UV-stable sealer so Florida moisture stays out and it doesn&rsquo;t start flaking again."),
            ("How often should I re-seal my concrete in this climate?", "More often than most people think, because the Gulf Coast sun and our wet season are hard on sealer. For decorative or stamped surfaces in full sun &mdash; pool decks, exposed patios &mdash; plan on a re-seal every two to three years to keep the color rich and moisture out of the slab. Plain broom-finished driveways and walkways can stretch a little longer, maybe three to five years, but a quick test tells the truth: splash water on the surface, and if it soaks in dark instead of beading, the sealer&rsquo;s spent. Re-sealing on schedule is cheap insurance &mdash; it&rsquo;s what prevents the spalling, staining, and fading that turn a quick re-coat into a full resurfacing job down the road."),
        ],
    },
}
