# Service data — part 4: pool deck pavers & paver sealing/restoration
SERVICES = {
    "pool-deck-pavers": {
        "name": "Pool Deck Pavers &amp; Travertine",
        "slug": "pool-deck-pavers",
        "short": "Pool Deck Pavers",
        "h1_phrase": "Pool Deck Pavers &amp; Travertine",
        "card_image": "card-pool-deck-pavers.webp",
        "icon": "09",
        "intro_lead": "Travertine, brick, and concrete pavers laid around your pool — cool underfoot in July, set on a compacted base that holds true through our sandy soil and summer storms.",
        "intro_long_p1": "A pool deck is the one surface in a Lakewood Ranch backyard that gets walked on barefoot, wet, in the middle of a Florida afternoon &mdash; and that is exactly where a poured concrete or dark-paver deck fails the people using it. <strong>Surface temperature is the whole conversation</strong>, and we have it honestly before we quote a single square foot. Light-toned travertine and ivory concrete pavers can run twenty to thirty degrees cooler than broom-finished concrete in direct sun, which is the difference between a deck your kids run across and one nobody touches without sandals. The second conversation is the base. Our sandy, fast-draining soil and the salt-and-chlorine splash off the pool will heave and stain a deck that was set on a lazy base, so every install follows the <strong>Lakewood Ranch Concrete 42-Point Install Standard</strong> &mdash; compacted limerock, proper slope away from the coping, and a bedding layer that drains instead of trapping water against your home. In an ARC-governed neighborhood like Country Club East or Esplanade, we also pull the approved color and pattern list before you fall in love with a paver the board will reject. <strong>Estimates are free</strong> and financing is available so the deck gets built once, right.",
        "intro_long_p2": "We build pool decks on three materials and we will tell you which one actually earns its price in your yard. <strong>Travertine</strong> is the premium pick &mdash; a natural stone that stays remarkably cool, wears a honed, slip-friendly face, and reads high-end against screen enclosures and spillover spas; its only honest caveat is that it is porous and wants sealing against salt and chlorine. <strong>Concrete pavers</strong> are the volume choice: dense, dimensionally consistent, available in tumbled and smooth faces, and easy to lift-and-reset if a tree root or settle ever shows up. <strong>Clay brick pavers</strong> hold their color for decades and suit a traditional elevation. Whatever the face, the joints get filled with <strong>polymeric sand</strong> &mdash; not loose mason sand &mdash; so ants, weeds, and pressure-washing do not empty them out by the next season. We set the perimeter and any spillover edges first, run the field to the drains, and finish with a bond beam or restraint edge so the deck cannot creep apart at the very pivot points that take the most foot traffic.",
        "scope_items": [
            "Travertine pool deck installation (honed, slip-friendly face)",
            "Concrete paver pool decks (tumbled &amp; smooth)",
            "Clay brick paver pool decks",
            "Pool coping &amp; bullnose edge work",
            "Spillover spa &amp; raised-bond-beam paver detailing",
            "Compacted limerock base to the 42-Point Standard",
            "Proper slope &amp; drainage away from coping &amp; home",
            "Paver-over-existing-concrete overlay where slab is sound",
            "Screen-enclosure &amp; cage-footer tie-in",
            "Polymeric sand joint filling",
            "Edge restraint &amp; perimeter bond beam",
            "Paver banding &amp; border accent patterns",
            "ARC / HOA color &amp; pattern submittal prep",
            "Penetrating sealer application on travertine &amp; pavers",
            "Site cleanup &amp; haul-away of demo material",
        ],
        "pricing_rows": [
            ("Concrete Paver Pool Deck", "$16&ndash;$24/sq ft installed", "Tumbled or smooth, on new compacted base"),
            ("Travertine Pool Deck", "$22&ndash;$32/sq ft installed", "Premium cool-touch natural stone"),
            ("Clay Brick Paver Deck", "$18&ndash;$26/sq ft installed", "Color-fast, traditional elevation"),
            ("Paver Overlay on Sound Concrete", "$14&ndash;$20/sq ft", "When existing slab passes inspection"),
            ("Pool Coping (per linear ft)", "$28&ndash;$48/lin ft", "Bullnose or square edge to match"),
            ("Spillover / Raised Bond Beam", "$45&ndash;$85/lin ft", "Spa &amp; planter edge detailing"),
            ("Old Deck Demo &amp; Haul", "$3&ndash;$6/sq ft", "Tear-out of broken concrete or pavers"),
            ("Penetrating Sealer (at install)", "$1.25&ndash;$2.50/sq ft", "Salt &amp; chlorine protection, breathable"),
        ],
        "faqs": [
            ("Does travertine really stay cool enough for bare feet?", "Yes &mdash; and it is the main reason we install so much of it around Lakewood Ranch pools. Light, ivory-toned travertine reflects sun rather than absorbing it, so in a direct July afternoon it commonly runs twenty to thirty degrees cooler than broom-finished concrete or a dark paver. It will never be cold, and no surface in full Florida sun is truly cool at 2 p.m., but the difference between travertine and standard concrete is the difference between walking across comfortably and hopping. Color matters as much as the material: a pale travertine or ivory concrete paver stays usable, a charcoal paver does not. We will show you actual samples in your own sun before you choose."),
            ("How often does a paver or travertine pool deck need sealing?", "Plan on resealing every two to three years, and travertine on the shorter end because it is naturally porous. The pool environment is hard on any deck &mdash; chlorine, salt spray, sunscreen, and constant wet-dry cycling all pull at the surface and the joints. A breathable penetrating sealer soaks in, repels salt and stains, and helps lock the polymeric sand without leaving a slick film. We do not recommend a glossy film-forming sealer on a wet pool deck because it can get slippery; the honest call here is a matte penetrating product. If your deck still beads water and the joints are full, you can wait; once it darkens when wet or the sand washes low, it is time."),
            ("What keeps weeds and ants out of the joints?", "Polymeric sand &mdash; and it is non-negotiable on our installs. Ordinary mason sand washes out under rain and pressure-washing, and the open joints then invite weeds, ants, and shifting pavers. Polymeric sand is swept into the joints and activated with a light mist so it firms up into a flexible, locked binder that resists washout, weeds, and insects while still letting the deck breathe and drain. Around a pool, where the deck gets soaked daily and cleaned often, this is what keeps the surface tight for years instead of months. When it eventually wears low, it is re-swept and re-activated &mdash; not torn out &mdash; which is part of our paver restoration service."),
            ("Is a paver pool deck slippery when wet?", "Less than you would expect, when it is built right. Pavers and tumbled travertine have a textured, honed face and the joint lines themselves break up sheeting water, so they grip better wet than a smooth troweled-concrete deck. The two things that actually create a slip risk are the wrong sealer &mdash; a glossy film-forming product over a constantly wet surface &mdash; and standing water from a deck that was never sloped to drain. We handle both at install: a matte penetrating sealer that does not change the traction, and a base graded to carry water off the deck and away from your coping and home rather than letting it pool where people walk."),
        ],
    },
    "paver-sealing": {
        "name": "Paver Sealing &amp; Restoration",
        "slug": "paver-sealing",
        "short": "Paver Sealing",
        "h1_phrase": "Paver Sealing &amp; Restoration",
        "card_image": "card-paver-sealing.webp",
        "icon": "10",
        "intro_lead": "Cleaning, re-sanding, re-leveling, and sealing tired pavers across Bradenton and Lakewood Ranch &mdash; bringing a faded, weed-grown driveway or pool deck back to the day it was laid.",
        "intro_long_p1": "Most paver problems we are called to fix are not the pavers &mdash; they are the joints and the seal that nobody maintained. A Lakewood Ranch driveway or pool deck that looks tired after five Florida summers is almost always sound underneath: the color has gone chalky from UV, the joint sand has washed low, weeds and ants have moved into the gaps, and <strong>white efflorescence</strong> &mdash; the natural salt haze that rises out of concrete pavers &mdash; has dulled the surface. Our sandy soil drains fast but also lets pavers settle at the very spots that take weight, so a few high or low pavers near a tire path or pool edge are normal wear, not a failure. Restoration handles all of it without tearing the deck out. We follow the cleaning-and-sealing sequence in the <strong>Lakewood Ranch Concrete 42-Point Install Standard</strong>, and in an ARC neighborhood we keep the finished look within the board-approved palette so a freshly sealed driveway does not trigger a letter. <strong>Estimates are free</strong> and financing is available for larger driveway-plus-deck packages.",
        "intro_long_p2": "Restoration is a sequence, and skipping a step is why DIY seal jobs go cloudy. First we <strong>pressure wash</strong> the whole surface to strip dirt, algae, old failing sealer, and surface efflorescence &mdash; a deep clean, not a rinse. Where pavers have settled or heaved, we <strong>lift, re-level the base, and reset</strong> them flush so the field is true again. Then every joint is refilled with <strong>polymeric sand</strong>, swept tight and activated so it locks against weeds, ants, and washout. Only once the deck is bone dry do we seal, and we match the sealer to the goal. A <strong>penetrating sealer</strong> soaks in, leaves a natural matte look, repels salt and stains, and breathes &mdash; our default for pool decks and anywhere slip matters. A <strong>film-forming sealer</strong> sits on top for a wet-look or satin sheen and a richer color, best on driveways and walkways. We will tell you plainly which suits your surface instead of glossing a pool deck that then turns slick.",
        "scope_items": [
            "Deep pressure washing &amp; surface prep",
            "Old / failing sealer stripping",
            "Efflorescence cleaning &amp; haze removal",
            "Weed, moss &amp; algae removal from joints",
            "Paver re-leveling &amp; reset of settled areas",
            "Sunken-paver base repair &amp; re-compaction",
            "Joint re-sanding with polymeric sand",
            "Cracked or broken paver replacement",
            "Penetrating sealer application (matte, breathable)",
            "Film-forming sealer application (wet-look or satin)",
            "Color-enhancing sealer where desired",
            "Edge restraint repair &amp; re-securing",
            "Oil &amp; rust stain treatment",
            "Driveway, walkway, lanai &amp; pool-deck restoration",
            "Final inspection &amp; care guidance",
        ],
        "pricing_rows": [
            ("Pressure Wash &amp; Clean Only", "$0.35&ndash;$0.75/sq ft", "Driveways, decks, walkways"),
            ("Clean, Re-Sand &amp; Penetrating Seal", "$1.25&ndash;$2.25/sq ft", "Most common restoration package"),
            ("Clean, Re-Sand &amp; Film-Forming Seal", "$1.75&ndash;$3/sq ft", "Wet-look or satin, richer color"),
            ("Polymeric Re-Sanding Only", "$0.60&ndash;$1.10/sq ft", "Joints refilled &amp; locked"),
            ("Paver Re-Leveling / Reset", "$8&ndash;$16/sq ft", "Settled or heaved sections, base repair"),
            ("Old Sealer Stripping", "+$0.50&ndash;$1.25/sq ft", "When prior film is failing or cloudy"),
            ("Broken Paver Replacement (each)", "$6&ndash;$18 per paver", "Color-matched as closely as stock allows"),
            ("Efflorescence / Stain Treatment", "$0.40&ndash;$0.90/sq ft", "Salt haze, oil, or rust"),
        ],
        "faqs": [
            ("How often should I have my pavers sealed?", "For most Bradenton and Lakewood Ranch surfaces, every two to three years &mdash; sooner for a pool deck that takes salt and chlorine daily, a little longer for a shaded walkway. Sealer is sacrificial: UV, rain, traffic, and our summer storms wear it off the top, and once it stops beading water and the color looks chalky, the surface is unprotected again. The honest test is simple &mdash; splash water on the pavers; if it soaks in and darkens the surface instead of beading, it is time. Resealing on schedule is far cheaper than letting efflorescence and ground-in stains set into bare pavers, which then need aggressive cleaning before any sealer will take."),
            ("My pavers have white haze on them &mdash; can that be fixed?", "Almost always, yes. That white film is efflorescence &mdash; natural salts inside the concrete paver rising to the surface as moisture evaporates, and it is extremely common on Florida pavers, especially newer ones. It is not damage and it does not mean the pavers are failing. We remove it with a dedicated efflorescence cleaner and a thorough pressure wash, then let the surface fully dry before sealing so the haze does not get locked in. The key detail people miss: you must clear efflorescence before sealing, never seal over it. A good penetrating sealer afterward slows how fast it returns, but on bare new pavers some recurrence is normal for the first year or two."),
            ("Do you re-sand the joints, and why does it matter?", "Yes &mdash; re-sanding is the step that makes a restoration last, and we use polymeric sand, not loose mason sand. Over a few Florida seasons, rain and pressure-washing pull the joint sand low, and empty joints let pavers shift, weeds sprout, and ants nest. We sweep fresh polymeric sand fully into the joints and activate it with a light mist so it firms into a flexible, locked binder that resists washout, weeds, and insects while still draining. Skipping this and sealing over low joints just glues in the problem. When pavers have already shifted from empty joints, we re-level those first, then re-sand &mdash; so the deck is tight before any sealer goes down."),
            ("Will sealing make my pool deck slippery?", "It can, if the wrong product is used &mdash; which is exactly why we match the sealer to the surface. On a pool deck we use a matte penetrating sealer that soaks into the pavers and leaves the natural texture and traction intact; it protects against salt and stains without laying a slick film on top. The glossy, wet-look film-forming sealers that look great on a driveway are the ones that can get slippery when wet, so we keep those off pool decks and high-splash lanais unless a non-slip additive is mixed in. If slip resistance is your priority, tell us up front and we will spec a penetrating product and, where it helps, a fine grip additive."),
        ],
    },
}
